
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Login: 'Login',
  ItemAccess: 'ItemAccess',
  SecureItem: 'SecureItem',
  VaultSecureItems: 'VaultSecureItems',
  Vault: 'Vault'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  phone: 'phone',
  authHash: 'authHash',
  securityToken: 'securityToken',
  enable2FA: 'enable2FA',
  twoFactorSecret: 'twoFactorSecret',
  recoveryCodes: 'recoveryCodes',
  publicKey: 'publicKey',
  encryptedPrivateKey: 'encryptedPrivateKey',
  createdAt: 'createdAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const LoginScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
} as const

export type LoginScalarFieldEnum = (typeof LoginScalarFieldEnum)[keyof typeof LoginScalarFieldEnum]


export const ItemAccessScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemId: 'itemId',
  encryptedRecordKey: 'encryptedRecordKey',
  isOwner: 'isOwner',
  createdAt: 'createdAt'
} as const

export type ItemAccessScalarFieldEnum = (typeof ItemAccessScalarFieldEnum)[keyof typeof ItemAccessScalarFieldEnum]


export const SecureItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  isCompromised: 'isCompromised',
  ciphertext: 'ciphertext',
  iv: 'iv',
  tag: 'tag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastScan: 'lastScan'
} as const

export type SecureItemScalarFieldEnum = (typeof SecureItemScalarFieldEnum)[keyof typeof SecureItemScalarFieldEnum]


export const VaultSecureItemsScalarFieldEnum = {
  vaultId: 'vaultId',
  itemId: 'itemId'
} as const

export type VaultSecureItemsScalarFieldEnum = (typeof VaultSecureItemsScalarFieldEnum)[keyof typeof VaultSecureItemsScalarFieldEnum]


export const VaultScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  title: 'title',
  icon: 'icon',
  enableMonitoring: 'enableMonitoring',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VaultScalarFieldEnum = (typeof VaultScalarFieldEnum)[keyof typeof VaultScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

