'use client';
import { toaster } from '@/components/ui/toaster';
import { getTwoFactorEnrollmentURI, handleEnrollTwoFactor } from '@/lib/user/userActions';
import { User } from '@/prisma/client';
import {
  Alert,
  Button,
  Card,
  Code,
  Collapsible,
  Field,
  Group,
  IconButton,
  Input,
  PinInput,
  QrCode,
  SimpleGrid,
  Stack,
  Text,
  VStack,
} from '@chakra-ui/react';
import { useRouter } from 'next/navigation';
import React from 'react';
import { TbAlertCircle, TbCopy, TbCopyCheck, TbDeviceFloppy } from 'react-icons/tb';

export default function TwoFactorForm({ user }: { user: User }) {
  const router = useRouter();

  const [enabled, setEnabled] = React.useState(user.enable2FA);
  const [totpSecret, setTotpSecret] = React.useState(user.twoFactorSecret ?? '');
  const [copiedSecret, setCopiedSecret] = React.useState(false);
  const [qrUri, setQrUri] = React.useState('');
  const [otpCode, setOtpCode] = React.useState<string[]>(['', '', '', '', '', '']);
  const [error, setError] = React.useState('');

  React.useEffect(() => {
    const generateUri = async () => {
      if (!enabled) {
        // generate an enrollment URI
        const uriScheme = await getTwoFactorEnrollmentURI();
        if (uriScheme.success) {
          setQrUri(uriScheme.data.uri);
          setTotpSecret(uriScheme.data.secret);
        } else {
          setError(uriScheme.error || 'Failed to generate QR code.');
        }
      }
    };
    generateUri();
  }, [enabled]);

  async function handleSubmit(e: React.SubmitEvent<HTMLFormElement>) {
    e.preventDefault();
    setError('');
    console.log(`[TwoFactorForm] Submitting TOTP code for enrollment: ${otpCode.join('')}`);
    const status = await handleEnrollTwoFactor(totpSecret, otpCode.join(''));
    console.log(`[TwoFactorForm] Enrollment status:`, status);
    if (status.success) {
      setEnabled(true);
      toaster.success({
        title: 'Two-Factor Authentication Enabled',
        description: 'You have successfully enabled two-factor authentication.',
      });
      router.refresh();
    } else {
      console.log('Failed to enable two-factor authentication:', status);
      setError(status.error || 'Failed to enable two-factor authentication.');
    }
  }

  const copySecret = () => {
    navigator.clipboard.writeText(totpSecret);
    setCopiedSecret(true);
    setTimeout(() => {
      setCopiedSecret(false);
    }, 2000);
  };

  const QRCode = (
    <QrCode.Root value={qrUri}>
      <QrCode.Frame>
        <QrCode.Pattern />
      </QrCode.Frame>
    </QrCode.Root>
  );

  if (!enabled) {
    return (
      <form onSubmit={handleSubmit}>
        <Card.Body>
          <Stack gap={4}>
            <Text>Scan the QR code below with your authenticator app to enable two-factor authentication.</Text>
            {QRCode}
            <Field.Root>
              <Group attached maxW="xs" w="full">
                <Input variant="subtle" value={totpSecret} readOnly />
                <IconButton variant="subtle" aria-label="Copy secret" onClick={copySecret}>
                  {copiedSecret ? <TbCopyCheck /> : <TbCopy />}
                </IconButton>
              </Group>
              <Field.HelperText>Can&apos;t scan the QR code? Use the secret key above.</Field.HelperText>
            </Field.Root>

            {error && (
              <Alert.Root>
                <Alert.Indicator>
                  <TbAlertCircle />
                </Alert.Indicator>
                <Alert.Title>Error</Alert.Title>
                <Alert.Description>{error}</Alert.Description>
              </Alert.Root>
            )}

            <Field.Root>
              <Field.Label>One-Time Password</Field.Label>
              <PinInput.Root
                value={otpCode}
                onValueChange={(v) => setOtpCode(v.value)}
                colorPalette="yellow"
                otp
                attached
              >
                <PinInput.HiddenInput />
                <PinInput.Control>
                  <PinInput.Input index={0} />
                  <PinInput.Input index={1} />
                  <PinInput.Input index={2} />
                  <PinInput.Input index={3} />
                  <PinInput.Input index={4} />
                  <PinInput.Input index={5} />
                </PinInput.Control>
              </PinInput.Root>
              <Field.HelperText>Enter the 6-digit code generated by your authenticator app.</Field.HelperText>
            </Field.Root>
          </Stack>
        </Card.Body>
        <Card.Footer>
          <Button colorPalette="yellow" type="submit">
            <TbDeviceFloppy />
            Verify and Enable
          </Button>
        </Card.Footer>
      </form>
    );
  }
  return (
    <Card.Body>
      <VStack gap={4}>
        <Text>
          Two-factor authentication is enabled for your account. To ensure you never lose access, make sure you make
          note of these recovery codes and store them in a safe place.
        </Text>
        <Collapsible.Root w="full">
          <Collapsible.Trigger asChild>
            <Button w="full" variant="surface">
              Show/Hide Recovery Codes
            </Button>
          </Collapsible.Trigger>
          <Collapsible.Content>
            <SimpleGrid columns={{ base: 1, sm: 2, lg: 3 }} w="full" bg="bg.muted" rounded="sm" p={4} mt={4} gap={4}>
              {user.recoveryCodes.split(',').map((code, index) => (
                <Code key={index}>{code}</Code>
              ))}
            </SimpleGrid>
          </Collapsible.Content>
        </Collapsible.Root>
      </VStack>
    </Card.Body>
  );
}
