
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ItemAccess` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ItemAccess
 * 
 */
export type ItemAccessModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemAccessPayload>

export type AggregateItemAccess = {
  _count: ItemAccessCountAggregateOutputType | null
  _min: ItemAccessMinAggregateOutputType | null
  _max: ItemAccessMaxAggregateOutputType | null
}

export type ItemAccessMinAggregateOutputType = {
  id: string | null
  userId: string | null
  itemId: string | null
  encryptedRecordKey: string | null
  isOwner: boolean | null
  createdAt: Date | null
}

export type ItemAccessMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  itemId: string | null
  encryptedRecordKey: string | null
  isOwner: boolean | null
  createdAt: Date | null
}

export type ItemAccessCountAggregateOutputType = {
  id: number
  userId: number
  itemId: number
  encryptedRecordKey: number
  isOwner: number
  createdAt: number
  _all: number
}


export type ItemAccessMinAggregateInputType = {
  id?: true
  userId?: true
  itemId?: true
  encryptedRecordKey?: true
  isOwner?: true
  createdAt?: true
}

export type ItemAccessMaxAggregateInputType = {
  id?: true
  userId?: true
  itemId?: true
  encryptedRecordKey?: true
  isOwner?: true
  createdAt?: true
}

export type ItemAccessCountAggregateInputType = {
  id?: true
  userId?: true
  itemId?: true
  encryptedRecordKey?: true
  isOwner?: true
  createdAt?: true
  _all?: true
}

export type ItemAccessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemAccess to aggregate.
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemAccesses to fetch.
   */
  orderBy?: Prisma.ItemAccessOrderByWithRelationInput | Prisma.ItemAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItemAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ItemAccesses
  **/
  _count?: true | ItemAccessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemAccessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemAccessMaxAggregateInputType
}

export type GetItemAccessAggregateType<T extends ItemAccessAggregateArgs> = {
      [P in keyof T & keyof AggregateItemAccess]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItemAccess[P]>
    : Prisma.GetScalarType<T[P], AggregateItemAccess[P]>
}




export type ItemAccessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemAccessWhereInput
  orderBy?: Prisma.ItemAccessOrderByWithAggregationInput | Prisma.ItemAccessOrderByWithAggregationInput[]
  by: Prisma.ItemAccessScalarFieldEnum[] | Prisma.ItemAccessScalarFieldEnum
  having?: Prisma.ItemAccessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemAccessCountAggregateInputType | true
  _min?: ItemAccessMinAggregateInputType
  _max?: ItemAccessMaxAggregateInputType
}

export type ItemAccessGroupByOutputType = {
  id: string
  userId: string
  itemId: string
  encryptedRecordKey: string
  isOwner: boolean
  createdAt: Date
  _count: ItemAccessCountAggregateOutputType | null
  _min: ItemAccessMinAggregateOutputType | null
  _max: ItemAccessMaxAggregateOutputType | null
}

export type GetItemAccessGroupByPayload<T extends ItemAccessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemAccessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemAccessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemAccessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemAccessGroupByOutputType[P]>
      }
    >
  >



export type ItemAccessWhereInput = {
  AND?: Prisma.ItemAccessWhereInput | Prisma.ItemAccessWhereInput[]
  OR?: Prisma.ItemAccessWhereInput[]
  NOT?: Prisma.ItemAccessWhereInput | Prisma.ItemAccessWhereInput[]
  id?: Prisma.StringFilter<"ItemAccess"> | string
  userId?: Prisma.StringFilter<"ItemAccess"> | string
  itemId?: Prisma.StringFilter<"ItemAccess"> | string
  encryptedRecordKey?: Prisma.StringFilter<"ItemAccess"> | string
  isOwner?: Prisma.BoolFilter<"ItemAccess"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ItemAccess"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  item?: Prisma.XOR<Prisma.SecureItemScalarRelationFilter, Prisma.SecureItemWhereInput>
}

export type ItemAccessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  encryptedRecordKey?: Prisma.SortOrder
  isOwner?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  item?: Prisma.SecureItemOrderByWithRelationInput
}

export type ItemAccessWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_itemId?: Prisma.ItemAccessUserIdItemIdCompoundUniqueInput
  AND?: Prisma.ItemAccessWhereInput | Prisma.ItemAccessWhereInput[]
  OR?: Prisma.ItemAccessWhereInput[]
  NOT?: Prisma.ItemAccessWhereInput | Prisma.ItemAccessWhereInput[]
  userId?: Prisma.StringFilter<"ItemAccess"> | string
  itemId?: Prisma.StringFilter<"ItemAccess"> | string
  encryptedRecordKey?: Prisma.StringFilter<"ItemAccess"> | string
  isOwner?: Prisma.BoolFilter<"ItemAccess"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ItemAccess"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  item?: Prisma.XOR<Prisma.SecureItemScalarRelationFilter, Prisma.SecureItemWhereInput>
}, "id" | "userId_itemId">

export type ItemAccessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  encryptedRecordKey?: Prisma.SortOrder
  isOwner?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ItemAccessCountOrderByAggregateInput
  _max?: Prisma.ItemAccessMaxOrderByAggregateInput
  _min?: Prisma.ItemAccessMinOrderByAggregateInput
}

export type ItemAccessScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItemAccessScalarWhereWithAggregatesInput | Prisma.ItemAccessScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItemAccessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItemAccessScalarWhereWithAggregatesInput | Prisma.ItemAccessScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ItemAccess"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ItemAccess"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"ItemAccess"> | string
  encryptedRecordKey?: Prisma.StringWithAggregatesFilter<"ItemAccess"> | string
  isOwner?: Prisma.BoolWithAggregatesFilter<"ItemAccess"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ItemAccess"> | Date | string
}

export type ItemAccessCreateInput = {
  id?: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutItemAccessInput
  item: Prisma.SecureItemCreateNestedOneWithoutAccessorsInput
}

export type ItemAccessUncheckedCreateInput = {
  id?: string
  userId: string
  itemId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutItemAccessNestedInput
  item?: Prisma.SecureItemUpdateOneRequiredWithoutAccessorsNestedInput
}

export type ItemAccessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessCreateManyInput = {
  id?: string
  userId: string
  itemId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessListRelationFilter = {
  every?: Prisma.ItemAccessWhereInput
  some?: Prisma.ItemAccessWhereInput
  none?: Prisma.ItemAccessWhereInput
}

export type ItemAccessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemAccessUserIdItemIdCompoundUniqueInput = {
  userId: string
  itemId: string
}

export type ItemAccessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  encryptedRecordKey?: Prisma.SortOrder
  isOwner?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemAccessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  encryptedRecordKey?: Prisma.SortOrder
  isOwner?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemAccessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  encryptedRecordKey?: Prisma.SortOrder
  isOwner?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemAccessCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput> | Prisma.ItemAccessCreateWithoutUserInput[] | Prisma.ItemAccessUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutUserInput | Prisma.ItemAccessCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ItemAccessCreateManyUserInputEnvelope
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
}

export type ItemAccessUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput> | Prisma.ItemAccessCreateWithoutUserInput[] | Prisma.ItemAccessUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutUserInput | Prisma.ItemAccessCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ItemAccessCreateManyUserInputEnvelope
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
}

export type ItemAccessUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput> | Prisma.ItemAccessCreateWithoutUserInput[] | Prisma.ItemAccessUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutUserInput | Prisma.ItemAccessCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ItemAccessUpsertWithWhereUniqueWithoutUserInput | Prisma.ItemAccessUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ItemAccessCreateManyUserInputEnvelope
  set?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  disconnect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  delete?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  update?: Prisma.ItemAccessUpdateWithWhereUniqueWithoutUserInput | Prisma.ItemAccessUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ItemAccessUpdateManyWithWhereWithoutUserInput | Prisma.ItemAccessUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
}

export type ItemAccessUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput> | Prisma.ItemAccessCreateWithoutUserInput[] | Prisma.ItemAccessUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutUserInput | Prisma.ItemAccessCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ItemAccessUpsertWithWhereUniqueWithoutUserInput | Prisma.ItemAccessUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ItemAccessCreateManyUserInputEnvelope
  set?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  disconnect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  delete?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  update?: Prisma.ItemAccessUpdateWithWhereUniqueWithoutUserInput | Prisma.ItemAccessUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ItemAccessUpdateManyWithWhereWithoutUserInput | Prisma.ItemAccessUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
}

export type ItemAccessCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput> | Prisma.ItemAccessCreateWithoutItemInput[] | Prisma.ItemAccessUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutItemInput | Prisma.ItemAccessCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.ItemAccessCreateManyItemInputEnvelope
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
}

export type ItemAccessUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput> | Prisma.ItemAccessCreateWithoutItemInput[] | Prisma.ItemAccessUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutItemInput | Prisma.ItemAccessCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.ItemAccessCreateManyItemInputEnvelope
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
}

export type ItemAccessUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput> | Prisma.ItemAccessCreateWithoutItemInput[] | Prisma.ItemAccessUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutItemInput | Prisma.ItemAccessCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.ItemAccessUpsertWithWhereUniqueWithoutItemInput | Prisma.ItemAccessUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.ItemAccessCreateManyItemInputEnvelope
  set?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  disconnect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  delete?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  update?: Prisma.ItemAccessUpdateWithWhereUniqueWithoutItemInput | Prisma.ItemAccessUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.ItemAccessUpdateManyWithWhereWithoutItemInput | Prisma.ItemAccessUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
}

export type ItemAccessUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput> | Prisma.ItemAccessCreateWithoutItemInput[] | Prisma.ItemAccessUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemAccessCreateOrConnectWithoutItemInput | Prisma.ItemAccessCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.ItemAccessUpsertWithWhereUniqueWithoutItemInput | Prisma.ItemAccessUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.ItemAccessCreateManyItemInputEnvelope
  set?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  disconnect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  delete?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  connect?: Prisma.ItemAccessWhereUniqueInput | Prisma.ItemAccessWhereUniqueInput[]
  update?: Prisma.ItemAccessUpdateWithWhereUniqueWithoutItemInput | Prisma.ItemAccessUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.ItemAccessUpdateManyWithWhereWithoutItemInput | Prisma.ItemAccessUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
}

export type ItemAccessCreateWithoutUserInput = {
  id?: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
  item: Prisma.SecureItemCreateNestedOneWithoutAccessorsInput
}

export type ItemAccessUncheckedCreateWithoutUserInput = {
  id?: string
  itemId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessCreateOrConnectWithoutUserInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput>
}

export type ItemAccessCreateManyUserInputEnvelope = {
  data: Prisma.ItemAccessCreateManyUserInput | Prisma.ItemAccessCreateManyUserInput[]
}

export type ItemAccessUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemAccessUpdateWithoutUserInput, Prisma.ItemAccessUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ItemAccessCreateWithoutUserInput, Prisma.ItemAccessUncheckedCreateWithoutUserInput>
}

export type ItemAccessUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemAccessUpdateWithoutUserInput, Prisma.ItemAccessUncheckedUpdateWithoutUserInput>
}

export type ItemAccessUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ItemAccessScalarWhereInput
  data: Prisma.XOR<Prisma.ItemAccessUpdateManyMutationInput, Prisma.ItemAccessUncheckedUpdateManyWithoutUserInput>
}

export type ItemAccessScalarWhereInput = {
  AND?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
  OR?: Prisma.ItemAccessScalarWhereInput[]
  NOT?: Prisma.ItemAccessScalarWhereInput | Prisma.ItemAccessScalarWhereInput[]
  id?: Prisma.StringFilter<"ItemAccess"> | string
  userId?: Prisma.StringFilter<"ItemAccess"> | string
  itemId?: Prisma.StringFilter<"ItemAccess"> | string
  encryptedRecordKey?: Prisma.StringFilter<"ItemAccess"> | string
  isOwner?: Prisma.BoolFilter<"ItemAccess"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ItemAccess"> | Date | string
}

export type ItemAccessCreateWithoutItemInput = {
  id?: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutItemAccessInput
}

export type ItemAccessUncheckedCreateWithoutItemInput = {
  id?: string
  userId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessCreateOrConnectWithoutItemInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput>
}

export type ItemAccessCreateManyItemInputEnvelope = {
  data: Prisma.ItemAccessCreateManyItemInput | Prisma.ItemAccessCreateManyItemInput[]
}

export type ItemAccessUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemAccessUpdateWithoutItemInput, Prisma.ItemAccessUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.ItemAccessCreateWithoutItemInput, Prisma.ItemAccessUncheckedCreateWithoutItemInput>
}

export type ItemAccessUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.ItemAccessWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemAccessUpdateWithoutItemInput, Prisma.ItemAccessUncheckedUpdateWithoutItemInput>
}

export type ItemAccessUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.ItemAccessScalarWhereInput
  data: Prisma.XOR<Prisma.ItemAccessUpdateManyMutationInput, Prisma.ItemAccessUncheckedUpdateManyWithoutItemInput>
}

export type ItemAccessCreateManyUserInput = {
  id?: string
  itemId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  item?: Prisma.SecureItemUpdateOneRequiredWithoutAccessorsNestedInput
}

export type ItemAccessUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessCreateManyItemInput = {
  id?: string
  userId: string
  encryptedRecordKey: string
  isOwner?: boolean
  createdAt?: Date | string
}

export type ItemAccessUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutItemAccessNestedInput
}

export type ItemAccessUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemAccessUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  encryptedRecordKey?: Prisma.StringFieldUpdateOperationsInput | string
  isOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ItemAccessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  itemId?: boolean
  encryptedRecordKey?: boolean
  isOwner?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemAccess"]>

export type ItemAccessSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  itemId?: boolean
  encryptedRecordKey?: boolean
  isOwner?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemAccess"]>

export type ItemAccessSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  itemId?: boolean
  encryptedRecordKey?: boolean
  isOwner?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemAccess"]>

export type ItemAccessSelectScalar = {
  id?: boolean
  userId?: boolean
  itemId?: boolean
  encryptedRecordKey?: boolean
  isOwner?: boolean
  createdAt?: boolean
}

export type ItemAccessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "itemId" | "encryptedRecordKey" | "isOwner" | "createdAt", ExtArgs["result"]["itemAccess"]>
export type ItemAccessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}
export type ItemAccessIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}
export type ItemAccessIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
}

export type $ItemAccessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ItemAccess"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    item: Prisma.$SecureItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    itemId: string
    encryptedRecordKey: string
    isOwner: boolean
    createdAt: Date
  }, ExtArgs["result"]["itemAccess"]>
  composites: {}
}

export type ItemAccessGetPayload<S extends boolean | null | undefined | ItemAccessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload, S>

export type ItemAccessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItemAccessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItemAccessCountAggregateInputType | true
  }

export interface ItemAccessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ItemAccess'], meta: { name: 'ItemAccess' } }
  /**
   * Find zero or one ItemAccess that matches the filter.
   * @param {ItemAccessFindUniqueArgs} args - Arguments to find a ItemAccess
   * @example
   * // Get one ItemAccess
   * const itemAccess = await prisma.itemAccess.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItemAccessFindUniqueArgs>(args: Prisma.SelectSubset<T, ItemAccessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ItemAccess that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItemAccessFindUniqueOrThrowArgs} args - Arguments to find a ItemAccess
   * @example
   * // Get one ItemAccess
   * const itemAccess = await prisma.itemAccess.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItemAccessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItemAccessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemAccess that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessFindFirstArgs} args - Arguments to find a ItemAccess
   * @example
   * // Get one ItemAccess
   * const itemAccess = await prisma.itemAccess.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItemAccessFindFirstArgs>(args?: Prisma.SelectSubset<T, ItemAccessFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemAccess that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessFindFirstOrThrowArgs} args - Arguments to find a ItemAccess
   * @example
   * // Get one ItemAccess
   * const itemAccess = await prisma.itemAccess.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItemAccessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItemAccessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ItemAccesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ItemAccesses
   * const itemAccesses = await prisma.itemAccess.findMany()
   * 
   * // Get first 10 ItemAccesses
   * const itemAccesses = await prisma.itemAccess.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemAccessWithIdOnly = await prisma.itemAccess.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItemAccessFindManyArgs>(args?: Prisma.SelectSubset<T, ItemAccessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ItemAccess.
   * @param {ItemAccessCreateArgs} args - Arguments to create a ItemAccess.
   * @example
   * // Create one ItemAccess
   * const ItemAccess = await prisma.itemAccess.create({
   *   data: {
   *     // ... data to create a ItemAccess
   *   }
   * })
   * 
   */
  create<T extends ItemAccessCreateArgs>(args: Prisma.SelectSubset<T, ItemAccessCreateArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ItemAccesses.
   * @param {ItemAccessCreateManyArgs} args - Arguments to create many ItemAccesses.
   * @example
   * // Create many ItemAccesses
   * const itemAccess = await prisma.itemAccess.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItemAccessCreateManyArgs>(args?: Prisma.SelectSubset<T, ItemAccessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ItemAccesses and returns the data saved in the database.
   * @param {ItemAccessCreateManyAndReturnArgs} args - Arguments to create many ItemAccesses.
   * @example
   * // Create many ItemAccesses
   * const itemAccess = await prisma.itemAccess.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ItemAccesses and only return the `id`
   * const itemAccessWithIdOnly = await prisma.itemAccess.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ItemAccessCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ItemAccessCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ItemAccess.
   * @param {ItemAccessDeleteArgs} args - Arguments to delete one ItemAccess.
   * @example
   * // Delete one ItemAccess
   * const ItemAccess = await prisma.itemAccess.delete({
   *   where: {
   *     // ... filter to delete one ItemAccess
   *   }
   * })
   * 
   */
  delete<T extends ItemAccessDeleteArgs>(args: Prisma.SelectSubset<T, ItemAccessDeleteArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ItemAccess.
   * @param {ItemAccessUpdateArgs} args - Arguments to update one ItemAccess.
   * @example
   * // Update one ItemAccess
   * const itemAccess = await prisma.itemAccess.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItemAccessUpdateArgs>(args: Prisma.SelectSubset<T, ItemAccessUpdateArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ItemAccesses.
   * @param {ItemAccessDeleteManyArgs} args - Arguments to filter ItemAccesses to delete.
   * @example
   * // Delete a few ItemAccesses
   * const { count } = await prisma.itemAccess.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItemAccessDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItemAccessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ItemAccesses
   * const itemAccess = await prisma.itemAccess.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItemAccessUpdateManyArgs>(args: Prisma.SelectSubset<T, ItemAccessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemAccesses and returns the data updated in the database.
   * @param {ItemAccessUpdateManyAndReturnArgs} args - Arguments to update many ItemAccesses.
   * @example
   * // Update many ItemAccesses
   * const itemAccess = await prisma.itemAccess.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ItemAccesses and only return the `id`
   * const itemAccessWithIdOnly = await prisma.itemAccess.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ItemAccessUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ItemAccessUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ItemAccess.
   * @param {ItemAccessUpsertArgs} args - Arguments to update or create a ItemAccess.
   * @example
   * // Update or create a ItemAccess
   * const itemAccess = await prisma.itemAccess.upsert({
   *   create: {
   *     // ... data to create a ItemAccess
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ItemAccess we want to update
   *   }
   * })
   */
  upsert<T extends ItemAccessUpsertArgs>(args: Prisma.SelectSubset<T, ItemAccessUpsertArgs<ExtArgs>>): Prisma.Prisma__ItemAccessClient<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ItemAccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessCountArgs} args - Arguments to filter ItemAccesses to count.
   * @example
   * // Count the number of ItemAccesses
   * const count = await prisma.itemAccess.count({
   *   where: {
   *     // ... the filter for the ItemAccesses we want to count
   *   }
   * })
  **/
  count<T extends ItemAccessCountArgs>(
    args?: Prisma.Subset<T, ItemAccessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemAccessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ItemAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemAccessAggregateArgs>(args: Prisma.Subset<T, ItemAccessAggregateArgs>): Prisma.PrismaPromise<GetItemAccessAggregateType<T>>

  /**
   * Group by ItemAccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemAccessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItemAccessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItemAccessGroupByArgs['orderBy'] }
      : { orderBy?: ItemAccessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItemAccessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemAccessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ItemAccess model
 */
readonly fields: ItemAccessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ItemAccess.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItemAccessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.SecureItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SecureItemDefaultArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ItemAccess model
 */
export interface ItemAccessFieldRefs {
  readonly id: Prisma.FieldRef<"ItemAccess", 'String'>
  readonly userId: Prisma.FieldRef<"ItemAccess", 'String'>
  readonly itemId: Prisma.FieldRef<"ItemAccess", 'String'>
  readonly encryptedRecordKey: Prisma.FieldRef<"ItemAccess", 'String'>
  readonly isOwner: Prisma.FieldRef<"ItemAccess", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ItemAccess", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ItemAccess findUnique
 */
export type ItemAccessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter, which ItemAccess to fetch.
   */
  where: Prisma.ItemAccessWhereUniqueInput
}

/**
 * ItemAccess findUniqueOrThrow
 */
export type ItemAccessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter, which ItemAccess to fetch.
   */
  where: Prisma.ItemAccessWhereUniqueInput
}

/**
 * ItemAccess findFirst
 */
export type ItemAccessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter, which ItemAccess to fetch.
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemAccesses to fetch.
   */
  orderBy?: Prisma.ItemAccessOrderByWithRelationInput | Prisma.ItemAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemAccesses.
   */
  cursor?: Prisma.ItemAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemAccesses.
   */
  distinct?: Prisma.ItemAccessScalarFieldEnum | Prisma.ItemAccessScalarFieldEnum[]
}

/**
 * ItemAccess findFirstOrThrow
 */
export type ItemAccessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter, which ItemAccess to fetch.
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemAccesses to fetch.
   */
  orderBy?: Prisma.ItemAccessOrderByWithRelationInput | Prisma.ItemAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemAccesses.
   */
  cursor?: Prisma.ItemAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemAccesses.
   */
  distinct?: Prisma.ItemAccessScalarFieldEnum | Prisma.ItemAccessScalarFieldEnum[]
}

/**
 * ItemAccess findMany
 */
export type ItemAccessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter, which ItemAccesses to fetch.
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemAccesses to fetch.
   */
  orderBy?: Prisma.ItemAccessOrderByWithRelationInput | Prisma.ItemAccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ItemAccesses.
   */
  cursor?: Prisma.ItemAccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemAccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemAccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemAccesses.
   */
  distinct?: Prisma.ItemAccessScalarFieldEnum | Prisma.ItemAccessScalarFieldEnum[]
}

/**
 * ItemAccess create
 */
export type ItemAccessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * The data needed to create a ItemAccess.
   */
  data: Prisma.XOR<Prisma.ItemAccessCreateInput, Prisma.ItemAccessUncheckedCreateInput>
}

/**
 * ItemAccess createMany
 */
export type ItemAccessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ItemAccesses.
   */
  data: Prisma.ItemAccessCreateManyInput | Prisma.ItemAccessCreateManyInput[]
}

/**
 * ItemAccess createManyAndReturn
 */
export type ItemAccessCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * The data used to create many ItemAccesses.
   */
  data: Prisma.ItemAccessCreateManyInput | Prisma.ItemAccessCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ItemAccess update
 */
export type ItemAccessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * The data needed to update a ItemAccess.
   */
  data: Prisma.XOR<Prisma.ItemAccessUpdateInput, Prisma.ItemAccessUncheckedUpdateInput>
  /**
   * Choose, which ItemAccess to update.
   */
  where: Prisma.ItemAccessWhereUniqueInput
}

/**
 * ItemAccess updateMany
 */
export type ItemAccessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ItemAccesses.
   */
  data: Prisma.XOR<Prisma.ItemAccessUpdateManyMutationInput, Prisma.ItemAccessUncheckedUpdateManyInput>
  /**
   * Filter which ItemAccesses to update
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * Limit how many ItemAccesses to update.
   */
  limit?: number
}

/**
 * ItemAccess updateManyAndReturn
 */
export type ItemAccessUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * The data used to update ItemAccesses.
   */
  data: Prisma.XOR<Prisma.ItemAccessUpdateManyMutationInput, Prisma.ItemAccessUncheckedUpdateManyInput>
  /**
   * Filter which ItemAccesses to update
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * Limit how many ItemAccesses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ItemAccess upsert
 */
export type ItemAccessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * The filter to search for the ItemAccess to update in case it exists.
   */
  where: Prisma.ItemAccessWhereUniqueInput
  /**
   * In case the ItemAccess found by the `where` argument doesn't exist, create a new ItemAccess with this data.
   */
  create: Prisma.XOR<Prisma.ItemAccessCreateInput, Prisma.ItemAccessUncheckedCreateInput>
  /**
   * In case the ItemAccess was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItemAccessUpdateInput, Prisma.ItemAccessUncheckedUpdateInput>
}

/**
 * ItemAccess delete
 */
export type ItemAccessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  /**
   * Filter which ItemAccess to delete.
   */
  where: Prisma.ItemAccessWhereUniqueInput
}

/**
 * ItemAccess deleteMany
 */
export type ItemAccessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemAccesses to delete
   */
  where?: Prisma.ItemAccessWhereInput
  /**
   * Limit how many ItemAccesses to delete.
   */
  limit?: number
}

/**
 * ItemAccess without action
 */
export type ItemAccessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
}
