
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LockerItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LockerItems
 * 
 */
export type LockerItemsModel = runtime.Types.Result.DefaultSelection<Prisma.$LockerItemsPayload>

export type AggregateLockerItems = {
  _count: LockerItemsCountAggregateOutputType | null
  _min: LockerItemsMinAggregateOutputType | null
  _max: LockerItemsMaxAggregateOutputType | null
}

export type LockerItemsMinAggregateOutputType = {
  lockerId: string | null
  itemId: string | null
}

export type LockerItemsMaxAggregateOutputType = {
  lockerId: string | null
  itemId: string | null
}

export type LockerItemsCountAggregateOutputType = {
  lockerId: number
  itemId: number
  _all: number
}


export type LockerItemsMinAggregateInputType = {
  lockerId?: true
  itemId?: true
}

export type LockerItemsMaxAggregateInputType = {
  lockerId?: true
  itemId?: true
}

export type LockerItemsCountAggregateInputType = {
  lockerId?: true
  itemId?: true
  _all?: true
}

export type LockerItemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LockerItems to aggregate.
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LockerItems to fetch.
   */
  orderBy?: Prisma.LockerItemsOrderByWithRelationInput | Prisma.LockerItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LockerItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LockerItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LockerItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LockerItems
  **/
  _count?: true | LockerItemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LockerItemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LockerItemsMaxAggregateInputType
}

export type GetLockerItemsAggregateType<T extends LockerItemsAggregateArgs> = {
      [P in keyof T & keyof AggregateLockerItems]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLockerItems[P]>
    : Prisma.GetScalarType<T[P], AggregateLockerItems[P]>
}




export type LockerItemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LockerItemsWhereInput
  orderBy?: Prisma.LockerItemsOrderByWithAggregationInput | Prisma.LockerItemsOrderByWithAggregationInput[]
  by: Prisma.LockerItemsScalarFieldEnum[] | Prisma.LockerItemsScalarFieldEnum
  having?: Prisma.LockerItemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LockerItemsCountAggregateInputType | true
  _min?: LockerItemsMinAggregateInputType
  _max?: LockerItemsMaxAggregateInputType
}

export type LockerItemsGroupByOutputType = {
  lockerId: string
  itemId: string
  _count: LockerItemsCountAggregateOutputType | null
  _min: LockerItemsMinAggregateOutputType | null
  _max: LockerItemsMaxAggregateOutputType | null
}

export type GetLockerItemsGroupByPayload<T extends LockerItemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LockerItemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LockerItemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LockerItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LockerItemsGroupByOutputType[P]>
      }
    >
  >



export type LockerItemsWhereInput = {
  AND?: Prisma.LockerItemsWhereInput | Prisma.LockerItemsWhereInput[]
  OR?: Prisma.LockerItemsWhereInput[]
  NOT?: Prisma.LockerItemsWhereInput | Prisma.LockerItemsWhereInput[]
  lockerId?: Prisma.StringFilter<"LockerItems"> | string
  itemId?: Prisma.StringFilter<"LockerItems"> | string
  locker?: Prisma.XOR<Prisma.LockerScalarRelationFilter, Prisma.LockerWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}

export type LockerItemsOrderByWithRelationInput = {
  lockerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  locker?: Prisma.LockerOrderByWithRelationInput
  item?: Prisma.ItemOrderByWithRelationInput
}

export type LockerItemsWhereUniqueInput = Prisma.AtLeast<{
  lockerId_itemId?: Prisma.LockerItemsLockerIdItemIdCompoundUniqueInput
  AND?: Prisma.LockerItemsWhereInput | Prisma.LockerItemsWhereInput[]
  OR?: Prisma.LockerItemsWhereInput[]
  NOT?: Prisma.LockerItemsWhereInput | Prisma.LockerItemsWhereInput[]
  lockerId?: Prisma.StringFilter<"LockerItems"> | string
  itemId?: Prisma.StringFilter<"LockerItems"> | string
  locker?: Prisma.XOR<Prisma.LockerScalarRelationFilter, Prisma.LockerWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}, "lockerId_itemId">

export type LockerItemsOrderByWithAggregationInput = {
  lockerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  _count?: Prisma.LockerItemsCountOrderByAggregateInput
  _max?: Prisma.LockerItemsMaxOrderByAggregateInput
  _min?: Prisma.LockerItemsMinOrderByAggregateInput
}

export type LockerItemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.LockerItemsScalarWhereWithAggregatesInput | Prisma.LockerItemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.LockerItemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LockerItemsScalarWhereWithAggregatesInput | Prisma.LockerItemsScalarWhereWithAggregatesInput[]
  lockerId?: Prisma.StringWithAggregatesFilter<"LockerItems"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"LockerItems"> | string
}

export type LockerItemsCreateInput = {
  locker: Prisma.LockerCreateNestedOneWithoutLockerItemsInput
  item: Prisma.ItemCreateNestedOneWithoutLockerItemsInput
}

export type LockerItemsUncheckedCreateInput = {
  lockerId: string
  itemId: string
}

export type LockerItemsUpdateInput = {
  locker?: Prisma.LockerUpdateOneRequiredWithoutLockerItemsNestedInput
  item?: Prisma.ItemUpdateOneRequiredWithoutLockerItemsNestedInput
}

export type LockerItemsUncheckedUpdateInput = {
  lockerId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LockerItemsCreateManyInput = {
  lockerId: string
  itemId: string
}

export type LockerItemsUpdateManyMutationInput = {

}

export type LockerItemsUncheckedUpdateManyInput = {
  lockerId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LockerItemsListRelationFilter = {
  every?: Prisma.LockerItemsWhereInput
  some?: Prisma.LockerItemsWhereInput
  none?: Prisma.LockerItemsWhereInput
}

export type LockerItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LockerItemsLockerIdItemIdCompoundUniqueInput = {
  lockerId: string
  itemId: string
}

export type LockerItemsCountOrderByAggregateInput = {
  lockerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type LockerItemsMaxOrderByAggregateInput = {
  lockerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type LockerItemsMinOrderByAggregateInput = {
  lockerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type LockerItemsCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput> | Prisma.LockerItemsCreateWithoutItemInput[] | Prisma.LockerItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutItemInput | Prisma.LockerItemsCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.LockerItemsCreateManyItemInputEnvelope
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
}

export type LockerItemsUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput> | Prisma.LockerItemsCreateWithoutItemInput[] | Prisma.LockerItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutItemInput | Prisma.LockerItemsCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.LockerItemsCreateManyItemInputEnvelope
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
}

export type LockerItemsUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput> | Prisma.LockerItemsCreateWithoutItemInput[] | Prisma.LockerItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutItemInput | Prisma.LockerItemsCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.LockerItemsUpsertWithWhereUniqueWithoutItemInput | Prisma.LockerItemsUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.LockerItemsCreateManyItemInputEnvelope
  set?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  disconnect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  delete?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  update?: Prisma.LockerItemsUpdateWithWhereUniqueWithoutItemInput | Prisma.LockerItemsUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.LockerItemsUpdateManyWithWhereWithoutItemInput | Prisma.LockerItemsUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
}

export type LockerItemsUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput> | Prisma.LockerItemsCreateWithoutItemInput[] | Prisma.LockerItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutItemInput | Prisma.LockerItemsCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.LockerItemsUpsertWithWhereUniqueWithoutItemInput | Prisma.LockerItemsUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.LockerItemsCreateManyItemInputEnvelope
  set?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  disconnect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  delete?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  update?: Prisma.LockerItemsUpdateWithWhereUniqueWithoutItemInput | Prisma.LockerItemsUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.LockerItemsUpdateManyWithWhereWithoutItemInput | Prisma.LockerItemsUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
}

export type LockerItemsCreateNestedManyWithoutLockerInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput> | Prisma.LockerItemsCreateWithoutLockerInput[] | Prisma.LockerItemsUncheckedCreateWithoutLockerInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutLockerInput | Prisma.LockerItemsCreateOrConnectWithoutLockerInput[]
  createMany?: Prisma.LockerItemsCreateManyLockerInputEnvelope
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
}

export type LockerItemsUncheckedCreateNestedManyWithoutLockerInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput> | Prisma.LockerItemsCreateWithoutLockerInput[] | Prisma.LockerItemsUncheckedCreateWithoutLockerInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutLockerInput | Prisma.LockerItemsCreateOrConnectWithoutLockerInput[]
  createMany?: Prisma.LockerItemsCreateManyLockerInputEnvelope
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
}

export type LockerItemsUpdateManyWithoutLockerNestedInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput> | Prisma.LockerItemsCreateWithoutLockerInput[] | Prisma.LockerItemsUncheckedCreateWithoutLockerInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutLockerInput | Prisma.LockerItemsCreateOrConnectWithoutLockerInput[]
  upsert?: Prisma.LockerItemsUpsertWithWhereUniqueWithoutLockerInput | Prisma.LockerItemsUpsertWithWhereUniqueWithoutLockerInput[]
  createMany?: Prisma.LockerItemsCreateManyLockerInputEnvelope
  set?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  disconnect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  delete?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  update?: Prisma.LockerItemsUpdateWithWhereUniqueWithoutLockerInput | Prisma.LockerItemsUpdateWithWhereUniqueWithoutLockerInput[]
  updateMany?: Prisma.LockerItemsUpdateManyWithWhereWithoutLockerInput | Prisma.LockerItemsUpdateManyWithWhereWithoutLockerInput[]
  deleteMany?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
}

export type LockerItemsUncheckedUpdateManyWithoutLockerNestedInput = {
  create?: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput> | Prisma.LockerItemsCreateWithoutLockerInput[] | Prisma.LockerItemsUncheckedCreateWithoutLockerInput[]
  connectOrCreate?: Prisma.LockerItemsCreateOrConnectWithoutLockerInput | Prisma.LockerItemsCreateOrConnectWithoutLockerInput[]
  upsert?: Prisma.LockerItemsUpsertWithWhereUniqueWithoutLockerInput | Prisma.LockerItemsUpsertWithWhereUniqueWithoutLockerInput[]
  createMany?: Prisma.LockerItemsCreateManyLockerInputEnvelope
  set?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  disconnect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  delete?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  connect?: Prisma.LockerItemsWhereUniqueInput | Prisma.LockerItemsWhereUniqueInput[]
  update?: Prisma.LockerItemsUpdateWithWhereUniqueWithoutLockerInput | Prisma.LockerItemsUpdateWithWhereUniqueWithoutLockerInput[]
  updateMany?: Prisma.LockerItemsUpdateManyWithWhereWithoutLockerInput | Prisma.LockerItemsUpdateManyWithWhereWithoutLockerInput[]
  deleteMany?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
}

export type LockerItemsCreateWithoutItemInput = {
  locker: Prisma.LockerCreateNestedOneWithoutLockerItemsInput
}

export type LockerItemsUncheckedCreateWithoutItemInput = {
  lockerId: string
}

export type LockerItemsCreateOrConnectWithoutItemInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput>
}

export type LockerItemsCreateManyItemInputEnvelope = {
  data: Prisma.LockerItemsCreateManyItemInput | Prisma.LockerItemsCreateManyItemInput[]
}

export type LockerItemsUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.LockerItemsUpdateWithoutItemInput, Prisma.LockerItemsUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.LockerItemsCreateWithoutItemInput, Prisma.LockerItemsUncheckedCreateWithoutItemInput>
}

export type LockerItemsUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.LockerItemsUpdateWithoutItemInput, Prisma.LockerItemsUncheckedUpdateWithoutItemInput>
}

export type LockerItemsUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.LockerItemsScalarWhereInput
  data: Prisma.XOR<Prisma.LockerItemsUpdateManyMutationInput, Prisma.LockerItemsUncheckedUpdateManyWithoutItemInput>
}

export type LockerItemsScalarWhereInput = {
  AND?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
  OR?: Prisma.LockerItemsScalarWhereInput[]
  NOT?: Prisma.LockerItemsScalarWhereInput | Prisma.LockerItemsScalarWhereInput[]
  lockerId?: Prisma.StringFilter<"LockerItems"> | string
  itemId?: Prisma.StringFilter<"LockerItems"> | string
}

export type LockerItemsCreateWithoutLockerInput = {
  item: Prisma.ItemCreateNestedOneWithoutLockerItemsInput
}

export type LockerItemsUncheckedCreateWithoutLockerInput = {
  itemId: string
}

export type LockerItemsCreateOrConnectWithoutLockerInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput>
}

export type LockerItemsCreateManyLockerInputEnvelope = {
  data: Prisma.LockerItemsCreateManyLockerInput | Prisma.LockerItemsCreateManyLockerInput[]
}

export type LockerItemsUpsertWithWhereUniqueWithoutLockerInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.LockerItemsUpdateWithoutLockerInput, Prisma.LockerItemsUncheckedUpdateWithoutLockerInput>
  create: Prisma.XOR<Prisma.LockerItemsCreateWithoutLockerInput, Prisma.LockerItemsUncheckedCreateWithoutLockerInput>
}

export type LockerItemsUpdateWithWhereUniqueWithoutLockerInput = {
  where: Prisma.LockerItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.LockerItemsUpdateWithoutLockerInput, Prisma.LockerItemsUncheckedUpdateWithoutLockerInput>
}

export type LockerItemsUpdateManyWithWhereWithoutLockerInput = {
  where: Prisma.LockerItemsScalarWhereInput
  data: Prisma.XOR<Prisma.LockerItemsUpdateManyMutationInput, Prisma.LockerItemsUncheckedUpdateManyWithoutLockerInput>
}

export type LockerItemsCreateManyItemInput = {
  lockerId: string
}

export type LockerItemsUpdateWithoutItemInput = {
  locker?: Prisma.LockerUpdateOneRequiredWithoutLockerItemsNestedInput
}

export type LockerItemsUncheckedUpdateWithoutItemInput = {
  lockerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LockerItemsUncheckedUpdateManyWithoutItemInput = {
  lockerId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LockerItemsCreateManyLockerInput = {
  itemId: string
}

export type LockerItemsUpdateWithoutLockerInput = {
  item?: Prisma.ItemUpdateOneRequiredWithoutLockerItemsNestedInput
}

export type LockerItemsUncheckedUpdateWithoutLockerInput = {
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LockerItemsUncheckedUpdateManyWithoutLockerInput = {
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type LockerItemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lockerId?: boolean
  itemId?: boolean
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lockerItems"]>

export type LockerItemsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lockerId?: boolean
  itemId?: boolean
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lockerItems"]>

export type LockerItemsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  lockerId?: boolean
  itemId?: boolean
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lockerItems"]>

export type LockerItemsSelectScalar = {
  lockerId?: boolean
  itemId?: boolean
}

export type LockerItemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"lockerId" | "itemId", ExtArgs["result"]["lockerItems"]>
export type LockerItemsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type LockerItemsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type LockerItemsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  locker?: boolean | Prisma.LockerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}

export type $LockerItemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LockerItems"
  objects: {
    locker: Prisma.$LockerPayload<ExtArgs>
    item: Prisma.$ItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    lockerId: string
    itemId: string
  }, ExtArgs["result"]["lockerItems"]>
  composites: {}
}

export type LockerItemsGetPayload<S extends boolean | null | undefined | LockerItemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload, S>

export type LockerItemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LockerItemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LockerItemsCountAggregateInputType | true
  }

export interface LockerItemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LockerItems'], meta: { name: 'LockerItems' } }
  /**
   * Find zero or one LockerItems that matches the filter.
   * @param {LockerItemsFindUniqueArgs} args - Arguments to find a LockerItems
   * @example
   * // Get one LockerItems
   * const lockerItems = await prisma.lockerItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LockerItemsFindUniqueArgs>(args: Prisma.SelectSubset<T, LockerItemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LockerItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LockerItemsFindUniqueOrThrowArgs} args - Arguments to find a LockerItems
   * @example
   * // Get one LockerItems
   * const lockerItems = await prisma.lockerItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LockerItemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LockerItemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LockerItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsFindFirstArgs} args - Arguments to find a LockerItems
   * @example
   * // Get one LockerItems
   * const lockerItems = await prisma.lockerItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LockerItemsFindFirstArgs>(args?: Prisma.SelectSubset<T, LockerItemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LockerItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsFindFirstOrThrowArgs} args - Arguments to find a LockerItems
   * @example
   * // Get one LockerItems
   * const lockerItems = await prisma.lockerItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LockerItemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LockerItemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LockerItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LockerItems
   * const lockerItems = await prisma.lockerItems.findMany()
   * 
   * // Get first 10 LockerItems
   * const lockerItems = await prisma.lockerItems.findMany({ take: 10 })
   * 
   * // Only select the `lockerId`
   * const lockerItemsWithLockerIdOnly = await prisma.lockerItems.findMany({ select: { lockerId: true } })
   * 
   */
  findMany<T extends LockerItemsFindManyArgs>(args?: Prisma.SelectSubset<T, LockerItemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LockerItems.
   * @param {LockerItemsCreateArgs} args - Arguments to create a LockerItems.
   * @example
   * // Create one LockerItems
   * const LockerItems = await prisma.lockerItems.create({
   *   data: {
   *     // ... data to create a LockerItems
   *   }
   * })
   * 
   */
  create<T extends LockerItemsCreateArgs>(args: Prisma.SelectSubset<T, LockerItemsCreateArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LockerItems.
   * @param {LockerItemsCreateManyArgs} args - Arguments to create many LockerItems.
   * @example
   * // Create many LockerItems
   * const lockerItems = await prisma.lockerItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LockerItemsCreateManyArgs>(args?: Prisma.SelectSubset<T, LockerItemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LockerItems and returns the data saved in the database.
   * @param {LockerItemsCreateManyAndReturnArgs} args - Arguments to create many LockerItems.
   * @example
   * // Create many LockerItems
   * const lockerItems = await prisma.lockerItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LockerItems and only return the `lockerId`
   * const lockerItemsWithLockerIdOnly = await prisma.lockerItems.createManyAndReturn({
   *   select: { lockerId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LockerItemsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LockerItemsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LockerItems.
   * @param {LockerItemsDeleteArgs} args - Arguments to delete one LockerItems.
   * @example
   * // Delete one LockerItems
   * const LockerItems = await prisma.lockerItems.delete({
   *   where: {
   *     // ... filter to delete one LockerItems
   *   }
   * })
   * 
   */
  delete<T extends LockerItemsDeleteArgs>(args: Prisma.SelectSubset<T, LockerItemsDeleteArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LockerItems.
   * @param {LockerItemsUpdateArgs} args - Arguments to update one LockerItems.
   * @example
   * // Update one LockerItems
   * const lockerItems = await prisma.lockerItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LockerItemsUpdateArgs>(args: Prisma.SelectSubset<T, LockerItemsUpdateArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LockerItems.
   * @param {LockerItemsDeleteManyArgs} args - Arguments to filter LockerItems to delete.
   * @example
   * // Delete a few LockerItems
   * const { count } = await prisma.lockerItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LockerItemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, LockerItemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LockerItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LockerItems
   * const lockerItems = await prisma.lockerItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LockerItemsUpdateManyArgs>(args: Prisma.SelectSubset<T, LockerItemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LockerItems and returns the data updated in the database.
   * @param {LockerItemsUpdateManyAndReturnArgs} args - Arguments to update many LockerItems.
   * @example
   * // Update many LockerItems
   * const lockerItems = await prisma.lockerItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LockerItems and only return the `lockerId`
   * const lockerItemsWithLockerIdOnly = await prisma.lockerItems.updateManyAndReturn({
   *   select: { lockerId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LockerItemsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LockerItemsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LockerItems.
   * @param {LockerItemsUpsertArgs} args - Arguments to update or create a LockerItems.
   * @example
   * // Update or create a LockerItems
   * const lockerItems = await prisma.lockerItems.upsert({
   *   create: {
   *     // ... data to create a LockerItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LockerItems we want to update
   *   }
   * })
   */
  upsert<T extends LockerItemsUpsertArgs>(args: Prisma.SelectSubset<T, LockerItemsUpsertArgs<ExtArgs>>): Prisma.Prisma__LockerItemsClient<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LockerItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsCountArgs} args - Arguments to filter LockerItems to count.
   * @example
   * // Count the number of LockerItems
   * const count = await prisma.lockerItems.count({
   *   where: {
   *     // ... the filter for the LockerItems we want to count
   *   }
   * })
  **/
  count<T extends LockerItemsCountArgs>(
    args?: Prisma.Subset<T, LockerItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LockerItemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LockerItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LockerItemsAggregateArgs>(args: Prisma.Subset<T, LockerItemsAggregateArgs>): Prisma.PrismaPromise<GetLockerItemsAggregateType<T>>

  /**
   * Group by LockerItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LockerItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LockerItemsGroupByArgs['orderBy'] }
      : { orderBy?: LockerItemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LockerItemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLockerItemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LockerItems model
 */
readonly fields: LockerItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LockerItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LockerItemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  locker<T extends Prisma.LockerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LockerDefaultArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.ItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LockerItems model
 */
export interface LockerItemsFieldRefs {
  readonly lockerId: Prisma.FieldRef<"LockerItems", 'String'>
  readonly itemId: Prisma.FieldRef<"LockerItems", 'String'>
}
    

// Custom InputTypes
/**
 * LockerItems findUnique
 */
export type LockerItemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter, which LockerItems to fetch.
   */
  where: Prisma.LockerItemsWhereUniqueInput
}

/**
 * LockerItems findUniqueOrThrow
 */
export type LockerItemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter, which LockerItems to fetch.
   */
  where: Prisma.LockerItemsWhereUniqueInput
}

/**
 * LockerItems findFirst
 */
export type LockerItemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter, which LockerItems to fetch.
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LockerItems to fetch.
   */
  orderBy?: Prisma.LockerItemsOrderByWithRelationInput | Prisma.LockerItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LockerItems.
   */
  cursor?: Prisma.LockerItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LockerItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LockerItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LockerItems.
   */
  distinct?: Prisma.LockerItemsScalarFieldEnum | Prisma.LockerItemsScalarFieldEnum[]
}

/**
 * LockerItems findFirstOrThrow
 */
export type LockerItemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter, which LockerItems to fetch.
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LockerItems to fetch.
   */
  orderBy?: Prisma.LockerItemsOrderByWithRelationInput | Prisma.LockerItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LockerItems.
   */
  cursor?: Prisma.LockerItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LockerItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LockerItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LockerItems.
   */
  distinct?: Prisma.LockerItemsScalarFieldEnum | Prisma.LockerItemsScalarFieldEnum[]
}

/**
 * LockerItems findMany
 */
export type LockerItemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter, which LockerItems to fetch.
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LockerItems to fetch.
   */
  orderBy?: Prisma.LockerItemsOrderByWithRelationInput | Prisma.LockerItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LockerItems.
   */
  cursor?: Prisma.LockerItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LockerItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LockerItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LockerItems.
   */
  distinct?: Prisma.LockerItemsScalarFieldEnum | Prisma.LockerItemsScalarFieldEnum[]
}

/**
 * LockerItems create
 */
export type LockerItemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * The data needed to create a LockerItems.
   */
  data: Prisma.XOR<Prisma.LockerItemsCreateInput, Prisma.LockerItemsUncheckedCreateInput>
}

/**
 * LockerItems createMany
 */
export type LockerItemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LockerItems.
   */
  data: Prisma.LockerItemsCreateManyInput | Prisma.LockerItemsCreateManyInput[]
}

/**
 * LockerItems createManyAndReturn
 */
export type LockerItemsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * The data used to create many LockerItems.
   */
  data: Prisma.LockerItemsCreateManyInput | Prisma.LockerItemsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LockerItems update
 */
export type LockerItemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * The data needed to update a LockerItems.
   */
  data: Prisma.XOR<Prisma.LockerItemsUpdateInput, Prisma.LockerItemsUncheckedUpdateInput>
  /**
   * Choose, which LockerItems to update.
   */
  where: Prisma.LockerItemsWhereUniqueInput
}

/**
 * LockerItems updateMany
 */
export type LockerItemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LockerItems.
   */
  data: Prisma.XOR<Prisma.LockerItemsUpdateManyMutationInput, Prisma.LockerItemsUncheckedUpdateManyInput>
  /**
   * Filter which LockerItems to update
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * Limit how many LockerItems to update.
   */
  limit?: number
}

/**
 * LockerItems updateManyAndReturn
 */
export type LockerItemsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * The data used to update LockerItems.
   */
  data: Prisma.XOR<Prisma.LockerItemsUpdateManyMutationInput, Prisma.LockerItemsUncheckedUpdateManyInput>
  /**
   * Filter which LockerItems to update
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * Limit how many LockerItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LockerItems upsert
 */
export type LockerItemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * The filter to search for the LockerItems to update in case it exists.
   */
  where: Prisma.LockerItemsWhereUniqueInput
  /**
   * In case the LockerItems found by the `where` argument doesn't exist, create a new LockerItems with this data.
   */
  create: Prisma.XOR<Prisma.LockerItemsCreateInput, Prisma.LockerItemsUncheckedCreateInput>
  /**
   * In case the LockerItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LockerItemsUpdateInput, Prisma.LockerItemsUncheckedUpdateInput>
}

/**
 * LockerItems delete
 */
export type LockerItemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  /**
   * Filter which LockerItems to delete.
   */
  where: Prisma.LockerItemsWhereUniqueInput
}

/**
 * LockerItems deleteMany
 */
export type LockerItemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LockerItems to delete
   */
  where?: Prisma.LockerItemsWhereInput
  /**
   * Limit how many LockerItems to delete.
   */
  limit?: number
}

/**
 * LockerItems without action
 */
export type LockerItemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
}
