
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Locker` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Locker
 * 
 */
export type LockerModel = runtime.Types.Result.DefaultSelection<Prisma.$LockerPayload>

export type AggregateLocker = {
  _count: LockerCountAggregateOutputType | null
  _min: LockerMinAggregateOutputType | null
  _max: LockerMaxAggregateOutputType | null
}

export type LockerMinAggregateOutputType = {
  id: string | null
  ownerId: string | null
  title: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LockerMaxAggregateOutputType = {
  id: string | null
  ownerId: string | null
  title: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type LockerCountAggregateOutputType = {
  id: number
  ownerId: number
  title: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type LockerMinAggregateInputType = {
  id?: true
  ownerId?: true
  title?: true
  createdAt?: true
  updatedAt?: true
}

export type LockerMaxAggregateInputType = {
  id?: true
  ownerId?: true
  title?: true
  createdAt?: true
  updatedAt?: true
}

export type LockerCountAggregateInputType = {
  id?: true
  ownerId?: true
  title?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type LockerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Locker to aggregate.
   */
  where?: Prisma.LockerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lockers to fetch.
   */
  orderBy?: Prisma.LockerOrderByWithRelationInput | Prisma.LockerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LockerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lockers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lockers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Lockers
  **/
  _count?: true | LockerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LockerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LockerMaxAggregateInputType
}

export type GetLockerAggregateType<T extends LockerAggregateArgs> = {
      [P in keyof T & keyof AggregateLocker]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLocker[P]>
    : Prisma.GetScalarType<T[P], AggregateLocker[P]>
}




export type LockerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LockerWhereInput
  orderBy?: Prisma.LockerOrderByWithAggregationInput | Prisma.LockerOrderByWithAggregationInput[]
  by: Prisma.LockerScalarFieldEnum[] | Prisma.LockerScalarFieldEnum
  having?: Prisma.LockerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LockerCountAggregateInputType | true
  _min?: LockerMinAggregateInputType
  _max?: LockerMaxAggregateInputType
}

export type LockerGroupByOutputType = {
  id: string
  ownerId: string
  title: string
  createdAt: Date
  updatedAt: Date
  _count: LockerCountAggregateOutputType | null
  _min: LockerMinAggregateOutputType | null
  _max: LockerMaxAggregateOutputType | null
}

export type GetLockerGroupByPayload<T extends LockerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LockerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LockerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LockerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LockerGroupByOutputType[P]>
      }
    >
  >



export type LockerWhereInput = {
  AND?: Prisma.LockerWhereInput | Prisma.LockerWhereInput[]
  OR?: Prisma.LockerWhereInput[]
  NOT?: Prisma.LockerWhereInput | Prisma.LockerWhereInput[]
  id?: Prisma.StringFilter<"Locker"> | string
  ownerId?: Prisma.StringFilter<"Locker"> | string
  title?: Prisma.StringFilter<"Locker"> | string
  createdAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
  lockerItems?: Prisma.LockerItemsListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LockerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lockerItems?: Prisma.LockerItemsOrderByRelationAggregateInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type LockerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LockerWhereInput | Prisma.LockerWhereInput[]
  OR?: Prisma.LockerWhereInput[]
  NOT?: Prisma.LockerWhereInput | Prisma.LockerWhereInput[]
  ownerId?: Prisma.StringFilter<"Locker"> | string
  title?: Prisma.StringFilter<"Locker"> | string
  createdAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
  lockerItems?: Prisma.LockerItemsListRelationFilter
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type LockerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LockerCountOrderByAggregateInput
  _max?: Prisma.LockerMaxOrderByAggregateInput
  _min?: Prisma.LockerMinOrderByAggregateInput
}

export type LockerScalarWhereWithAggregatesInput = {
  AND?: Prisma.LockerScalarWhereWithAggregatesInput | Prisma.LockerScalarWhereWithAggregatesInput[]
  OR?: Prisma.LockerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LockerScalarWhereWithAggregatesInput | Prisma.LockerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Locker"> | string
  ownerId?: Prisma.StringWithAggregatesFilter<"Locker"> | string
  title?: Prisma.StringWithAggregatesFilter<"Locker"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Locker"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Locker"> | Date | string
}

export type LockerCreateInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lockerItems?: Prisma.LockerItemsCreateNestedManyWithoutLockerInput
  user: Prisma.UserCreateNestedOneWithoutLockersInput
}

export type LockerUncheckedCreateInput = {
  id?: string
  ownerId: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lockerItems?: Prisma.LockerItemsUncheckedCreateNestedManyWithoutLockerInput
}

export type LockerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lockerItems?: Prisma.LockerItemsUpdateManyWithoutLockerNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutLockersNestedInput
}

export type LockerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lockerItems?: Prisma.LockerItemsUncheckedUpdateManyWithoutLockerNestedInput
}

export type LockerCreateManyInput = {
  id?: string
  ownerId: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LockerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LockerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LockerListRelationFilter = {
  every?: Prisma.LockerWhereInput
  some?: Prisma.LockerWhereInput
  none?: Prisma.LockerWhereInput
}

export type LockerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LockerScalarRelationFilter = {
  is?: Prisma.LockerWhereInput
  isNot?: Prisma.LockerWhereInput
}

export type LockerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LockerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LockerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LockerCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput> | Prisma.LockerCreateWithoutUserInput[] | Prisma.LockerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutUserInput | Prisma.LockerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LockerCreateManyUserInputEnvelope
  connect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
}

export type LockerUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput> | Prisma.LockerCreateWithoutUserInput[] | Prisma.LockerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutUserInput | Prisma.LockerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LockerCreateManyUserInputEnvelope
  connect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
}

export type LockerUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput> | Prisma.LockerCreateWithoutUserInput[] | Prisma.LockerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutUserInput | Prisma.LockerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LockerUpsertWithWhereUniqueWithoutUserInput | Prisma.LockerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LockerCreateManyUserInputEnvelope
  set?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  disconnect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  delete?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  connect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  update?: Prisma.LockerUpdateWithWhereUniqueWithoutUserInput | Prisma.LockerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LockerUpdateManyWithWhereWithoutUserInput | Prisma.LockerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LockerScalarWhereInput | Prisma.LockerScalarWhereInput[]
}

export type LockerUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput> | Prisma.LockerCreateWithoutUserInput[] | Prisma.LockerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutUserInput | Prisma.LockerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LockerUpsertWithWhereUniqueWithoutUserInput | Prisma.LockerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LockerCreateManyUserInputEnvelope
  set?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  disconnect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  delete?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  connect?: Prisma.LockerWhereUniqueInput | Prisma.LockerWhereUniqueInput[]
  update?: Prisma.LockerUpdateWithWhereUniqueWithoutUserInput | Prisma.LockerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LockerUpdateManyWithWhereWithoutUserInput | Prisma.LockerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LockerScalarWhereInput | Prisma.LockerScalarWhereInput[]
}

export type LockerCreateNestedOneWithoutLockerItemsInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutLockerItemsInput, Prisma.LockerUncheckedCreateWithoutLockerItemsInput>
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutLockerItemsInput
  connect?: Prisma.LockerWhereUniqueInput
}

export type LockerUpdateOneRequiredWithoutLockerItemsNestedInput = {
  create?: Prisma.XOR<Prisma.LockerCreateWithoutLockerItemsInput, Prisma.LockerUncheckedCreateWithoutLockerItemsInput>
  connectOrCreate?: Prisma.LockerCreateOrConnectWithoutLockerItemsInput
  upsert?: Prisma.LockerUpsertWithoutLockerItemsInput
  connect?: Prisma.LockerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LockerUpdateToOneWithWhereWithoutLockerItemsInput, Prisma.LockerUpdateWithoutLockerItemsInput>, Prisma.LockerUncheckedUpdateWithoutLockerItemsInput>
}

export type LockerCreateWithoutUserInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lockerItems?: Prisma.LockerItemsCreateNestedManyWithoutLockerInput
}

export type LockerUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lockerItems?: Prisma.LockerItemsUncheckedCreateNestedManyWithoutLockerInput
}

export type LockerCreateOrConnectWithoutUserInput = {
  where: Prisma.LockerWhereUniqueInput
  create: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput>
}

export type LockerCreateManyUserInputEnvelope = {
  data: Prisma.LockerCreateManyUserInput | Prisma.LockerCreateManyUserInput[]
}

export type LockerUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LockerWhereUniqueInput
  update: Prisma.XOR<Prisma.LockerUpdateWithoutUserInput, Prisma.LockerUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LockerCreateWithoutUserInput, Prisma.LockerUncheckedCreateWithoutUserInput>
}

export type LockerUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LockerWhereUniqueInput
  data: Prisma.XOR<Prisma.LockerUpdateWithoutUserInput, Prisma.LockerUncheckedUpdateWithoutUserInput>
}

export type LockerUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LockerScalarWhereInput
  data: Prisma.XOR<Prisma.LockerUpdateManyMutationInput, Prisma.LockerUncheckedUpdateManyWithoutUserInput>
}

export type LockerScalarWhereInput = {
  AND?: Prisma.LockerScalarWhereInput | Prisma.LockerScalarWhereInput[]
  OR?: Prisma.LockerScalarWhereInput[]
  NOT?: Prisma.LockerScalarWhereInput | Prisma.LockerScalarWhereInput[]
  id?: Prisma.StringFilter<"Locker"> | string
  ownerId?: Prisma.StringFilter<"Locker"> | string
  title?: Prisma.StringFilter<"Locker"> | string
  createdAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Locker"> | Date | string
}

export type LockerCreateWithoutLockerItemsInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLockersInput
}

export type LockerUncheckedCreateWithoutLockerItemsInput = {
  id?: string
  ownerId: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LockerCreateOrConnectWithoutLockerItemsInput = {
  where: Prisma.LockerWhereUniqueInput
  create: Prisma.XOR<Prisma.LockerCreateWithoutLockerItemsInput, Prisma.LockerUncheckedCreateWithoutLockerItemsInput>
}

export type LockerUpsertWithoutLockerItemsInput = {
  update: Prisma.XOR<Prisma.LockerUpdateWithoutLockerItemsInput, Prisma.LockerUncheckedUpdateWithoutLockerItemsInput>
  create: Prisma.XOR<Prisma.LockerCreateWithoutLockerItemsInput, Prisma.LockerUncheckedCreateWithoutLockerItemsInput>
  where?: Prisma.LockerWhereInput
}

export type LockerUpdateToOneWithWhereWithoutLockerItemsInput = {
  where?: Prisma.LockerWhereInput
  data: Prisma.XOR<Prisma.LockerUpdateWithoutLockerItemsInput, Prisma.LockerUncheckedUpdateWithoutLockerItemsInput>
}

export type LockerUpdateWithoutLockerItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLockersNestedInput
}

export type LockerUncheckedUpdateWithoutLockerItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LockerCreateManyUserInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type LockerUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lockerItems?: Prisma.LockerItemsUpdateManyWithoutLockerNestedInput
}

export type LockerUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lockerItems?: Prisma.LockerItemsUncheckedUpdateManyWithoutLockerNestedInput
}

export type LockerUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type LockerCountOutputType
 */

export type LockerCountOutputType = {
  lockerItems: number
}

export type LockerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lockerItems?: boolean | LockerCountOutputTypeCountLockerItemsArgs
}

/**
 * LockerCountOutputType without action
 */
export type LockerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerCountOutputType
   */
  select?: Prisma.LockerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LockerCountOutputType without action
 */
export type LockerCountOutputTypeCountLockerItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LockerItemsWhereInput
}


export type LockerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lockerItems?: boolean | Prisma.Locker$lockerItemsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.LockerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["locker"]>

export type LockerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["locker"]>

export type LockerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerId?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["locker"]>

export type LockerSelectScalar = {
  id?: boolean
  ownerId?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type LockerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ownerId" | "title" | "createdAt" | "updatedAt", ExtArgs["result"]["locker"]>
export type LockerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lockerItems?: boolean | Prisma.Locker$lockerItemsArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.LockerCountOutputTypeDefaultArgs<ExtArgs>
}
export type LockerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LockerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LockerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Locker"
  objects: {
    lockerItems: Prisma.$LockerItemsPayload<ExtArgs>[]
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ownerId: string
    title: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["locker"]>
  composites: {}
}

export type LockerGetPayload<S extends boolean | null | undefined | LockerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LockerPayload, S>

export type LockerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LockerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LockerCountAggregateInputType | true
  }

export interface LockerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Locker'], meta: { name: 'Locker' } }
  /**
   * Find zero or one Locker that matches the filter.
   * @param {LockerFindUniqueArgs} args - Arguments to find a Locker
   * @example
   * // Get one Locker
   * const locker = await prisma.locker.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LockerFindUniqueArgs>(args: Prisma.SelectSubset<T, LockerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Locker that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LockerFindUniqueOrThrowArgs} args - Arguments to find a Locker
   * @example
   * // Get one Locker
   * const locker = await prisma.locker.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LockerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LockerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Locker that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerFindFirstArgs} args - Arguments to find a Locker
   * @example
   * // Get one Locker
   * const locker = await prisma.locker.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LockerFindFirstArgs>(args?: Prisma.SelectSubset<T, LockerFindFirstArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Locker that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerFindFirstOrThrowArgs} args - Arguments to find a Locker
   * @example
   * // Get one Locker
   * const locker = await prisma.locker.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LockerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LockerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Lockers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Lockers
   * const lockers = await prisma.locker.findMany()
   * 
   * // Get first 10 Lockers
   * const lockers = await prisma.locker.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lockerWithIdOnly = await prisma.locker.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LockerFindManyArgs>(args?: Prisma.SelectSubset<T, LockerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Locker.
   * @param {LockerCreateArgs} args - Arguments to create a Locker.
   * @example
   * // Create one Locker
   * const Locker = await prisma.locker.create({
   *   data: {
   *     // ... data to create a Locker
   *   }
   * })
   * 
   */
  create<T extends LockerCreateArgs>(args: Prisma.SelectSubset<T, LockerCreateArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Lockers.
   * @param {LockerCreateManyArgs} args - Arguments to create many Lockers.
   * @example
   * // Create many Lockers
   * const locker = await prisma.locker.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LockerCreateManyArgs>(args?: Prisma.SelectSubset<T, LockerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Lockers and returns the data saved in the database.
   * @param {LockerCreateManyAndReturnArgs} args - Arguments to create many Lockers.
   * @example
   * // Create many Lockers
   * const locker = await prisma.locker.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Lockers and only return the `id`
   * const lockerWithIdOnly = await prisma.locker.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LockerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LockerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Locker.
   * @param {LockerDeleteArgs} args - Arguments to delete one Locker.
   * @example
   * // Delete one Locker
   * const Locker = await prisma.locker.delete({
   *   where: {
   *     // ... filter to delete one Locker
   *   }
   * })
   * 
   */
  delete<T extends LockerDeleteArgs>(args: Prisma.SelectSubset<T, LockerDeleteArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Locker.
   * @param {LockerUpdateArgs} args - Arguments to update one Locker.
   * @example
   * // Update one Locker
   * const locker = await prisma.locker.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LockerUpdateArgs>(args: Prisma.SelectSubset<T, LockerUpdateArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Lockers.
   * @param {LockerDeleteManyArgs} args - Arguments to filter Lockers to delete.
   * @example
   * // Delete a few Lockers
   * const { count } = await prisma.locker.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LockerDeleteManyArgs>(args?: Prisma.SelectSubset<T, LockerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lockers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Lockers
   * const locker = await prisma.locker.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LockerUpdateManyArgs>(args: Prisma.SelectSubset<T, LockerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lockers and returns the data updated in the database.
   * @param {LockerUpdateManyAndReturnArgs} args - Arguments to update many Lockers.
   * @example
   * // Update many Lockers
   * const locker = await prisma.locker.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Lockers and only return the `id`
   * const lockerWithIdOnly = await prisma.locker.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LockerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LockerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Locker.
   * @param {LockerUpsertArgs} args - Arguments to update or create a Locker.
   * @example
   * // Update or create a Locker
   * const locker = await prisma.locker.upsert({
   *   create: {
   *     // ... data to create a Locker
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Locker we want to update
   *   }
   * })
   */
  upsert<T extends LockerUpsertArgs>(args: Prisma.SelectSubset<T, LockerUpsertArgs<ExtArgs>>): Prisma.Prisma__LockerClient<runtime.Types.Result.GetResult<Prisma.$LockerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Lockers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerCountArgs} args - Arguments to filter Lockers to count.
   * @example
   * // Count the number of Lockers
   * const count = await prisma.locker.count({
   *   where: {
   *     // ... the filter for the Lockers we want to count
   *   }
   * })
  **/
  count<T extends LockerCountArgs>(
    args?: Prisma.Subset<T, LockerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LockerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Locker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LockerAggregateArgs>(args: Prisma.Subset<T, LockerAggregateArgs>): Prisma.PrismaPromise<GetLockerAggregateType<T>>

  /**
   * Group by Locker.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LockerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LockerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LockerGroupByArgs['orderBy'] }
      : { orderBy?: LockerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LockerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLockerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Locker model
 */
readonly fields: LockerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Locker.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LockerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lockerItems<T extends Prisma.Locker$lockerItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Locker$lockerItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LockerItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Locker model
 */
export interface LockerFieldRefs {
  readonly id: Prisma.FieldRef<"Locker", 'String'>
  readonly ownerId: Prisma.FieldRef<"Locker", 'String'>
  readonly title: Prisma.FieldRef<"Locker", 'String'>
  readonly createdAt: Prisma.FieldRef<"Locker", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Locker", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Locker findUnique
 */
export type LockerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter, which Locker to fetch.
   */
  where: Prisma.LockerWhereUniqueInput
}

/**
 * Locker findUniqueOrThrow
 */
export type LockerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter, which Locker to fetch.
   */
  where: Prisma.LockerWhereUniqueInput
}

/**
 * Locker findFirst
 */
export type LockerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter, which Locker to fetch.
   */
  where?: Prisma.LockerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lockers to fetch.
   */
  orderBy?: Prisma.LockerOrderByWithRelationInput | Prisma.LockerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lockers.
   */
  cursor?: Prisma.LockerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lockers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lockers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lockers.
   */
  distinct?: Prisma.LockerScalarFieldEnum | Prisma.LockerScalarFieldEnum[]
}

/**
 * Locker findFirstOrThrow
 */
export type LockerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter, which Locker to fetch.
   */
  where?: Prisma.LockerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lockers to fetch.
   */
  orderBy?: Prisma.LockerOrderByWithRelationInput | Prisma.LockerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Lockers.
   */
  cursor?: Prisma.LockerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lockers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lockers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lockers.
   */
  distinct?: Prisma.LockerScalarFieldEnum | Prisma.LockerScalarFieldEnum[]
}

/**
 * Locker findMany
 */
export type LockerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter, which Lockers to fetch.
   */
  where?: Prisma.LockerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Lockers to fetch.
   */
  orderBy?: Prisma.LockerOrderByWithRelationInput | Prisma.LockerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Lockers.
   */
  cursor?: Prisma.LockerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Lockers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Lockers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Lockers.
   */
  distinct?: Prisma.LockerScalarFieldEnum | Prisma.LockerScalarFieldEnum[]
}

/**
 * Locker create
 */
export type LockerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * The data needed to create a Locker.
   */
  data: Prisma.XOR<Prisma.LockerCreateInput, Prisma.LockerUncheckedCreateInput>
}

/**
 * Locker createMany
 */
export type LockerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Lockers.
   */
  data: Prisma.LockerCreateManyInput | Prisma.LockerCreateManyInput[]
}

/**
 * Locker createManyAndReturn
 */
export type LockerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * The data used to create many Lockers.
   */
  data: Prisma.LockerCreateManyInput | Prisma.LockerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Locker update
 */
export type LockerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * The data needed to update a Locker.
   */
  data: Prisma.XOR<Prisma.LockerUpdateInput, Prisma.LockerUncheckedUpdateInput>
  /**
   * Choose, which Locker to update.
   */
  where: Prisma.LockerWhereUniqueInput
}

/**
 * Locker updateMany
 */
export type LockerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Lockers.
   */
  data: Prisma.XOR<Prisma.LockerUpdateManyMutationInput, Prisma.LockerUncheckedUpdateManyInput>
  /**
   * Filter which Lockers to update
   */
  where?: Prisma.LockerWhereInput
  /**
   * Limit how many Lockers to update.
   */
  limit?: number
}

/**
 * Locker updateManyAndReturn
 */
export type LockerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * The data used to update Lockers.
   */
  data: Prisma.XOR<Prisma.LockerUpdateManyMutationInput, Prisma.LockerUncheckedUpdateManyInput>
  /**
   * Filter which Lockers to update
   */
  where?: Prisma.LockerWhereInput
  /**
   * Limit how many Lockers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Locker upsert
 */
export type LockerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * The filter to search for the Locker to update in case it exists.
   */
  where: Prisma.LockerWhereUniqueInput
  /**
   * In case the Locker found by the `where` argument doesn't exist, create a new Locker with this data.
   */
  create: Prisma.XOR<Prisma.LockerCreateInput, Prisma.LockerUncheckedCreateInput>
  /**
   * In case the Locker was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LockerUpdateInput, Prisma.LockerUncheckedUpdateInput>
}

/**
 * Locker delete
 */
export type LockerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
  /**
   * Filter which Locker to delete.
   */
  where: Prisma.LockerWhereUniqueInput
}

/**
 * Locker deleteMany
 */
export type LockerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lockers to delete
   */
  where?: Prisma.LockerWhereInput
  /**
   * Limit how many Lockers to delete.
   */
  limit?: number
}

/**
 * Locker.lockerItems
 */
export type Locker$lockerItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LockerItems
   */
  select?: Prisma.LockerItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LockerItems
   */
  omit?: Prisma.LockerItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerItemsInclude<ExtArgs> | null
  where?: Prisma.LockerItemsWhereInput
  orderBy?: Prisma.LockerItemsOrderByWithRelationInput | Prisma.LockerItemsOrderByWithRelationInput[]
  cursor?: Prisma.LockerItemsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LockerItemsScalarFieldEnum | Prisma.LockerItemsScalarFieldEnum[]
}

/**
 * Locker without action
 */
export type LockerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Locker
   */
  select?: Prisma.LockerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Locker
   */
  omit?: Prisma.LockerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LockerInclude<ExtArgs> | null
}
