
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SecureItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SecureItem
 * 
 */
export type SecureItemModel = runtime.Types.Result.DefaultSelection<Prisma.$SecureItemPayload>

export type AggregateSecureItem = {
  _count: SecureItemCountAggregateOutputType | null
  _min: SecureItemMinAggregateOutputType | null
  _max: SecureItemMaxAggregateOutputType | null
}

export type SecureItemMinAggregateOutputType = {
  id: string | null
  title: string | null
  category: string | null
  isCompromised: boolean | null
  ciphertext: string | null
  iv: string | null
  tag: string | null
  createdAt: Date | null
  updatedAt: Date | null
  lastScan: Date | null
}

export type SecureItemMaxAggregateOutputType = {
  id: string | null
  title: string | null
  category: string | null
  isCompromised: boolean | null
  ciphertext: string | null
  iv: string | null
  tag: string | null
  createdAt: Date | null
  updatedAt: Date | null
  lastScan: Date | null
}

export type SecureItemCountAggregateOutputType = {
  id: number
  title: number
  category: number
  isCompromised: number
  ciphertext: number
  iv: number
  tag: number
  createdAt: number
  updatedAt: number
  lastScan: number
  _all: number
}


export type SecureItemMinAggregateInputType = {
  id?: true
  title?: true
  category?: true
  isCompromised?: true
  ciphertext?: true
  iv?: true
  tag?: true
  createdAt?: true
  updatedAt?: true
  lastScan?: true
}

export type SecureItemMaxAggregateInputType = {
  id?: true
  title?: true
  category?: true
  isCompromised?: true
  ciphertext?: true
  iv?: true
  tag?: true
  createdAt?: true
  updatedAt?: true
  lastScan?: true
}

export type SecureItemCountAggregateInputType = {
  id?: true
  title?: true
  category?: true
  isCompromised?: true
  ciphertext?: true
  iv?: true
  tag?: true
  createdAt?: true
  updatedAt?: true
  lastScan?: true
  _all?: true
}

export type SecureItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SecureItem to aggregate.
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SecureItems to fetch.
   */
  orderBy?: Prisma.SecureItemOrderByWithRelationInput | Prisma.SecureItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SecureItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SecureItems
  **/
  _count?: true | SecureItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SecureItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SecureItemMaxAggregateInputType
}

export type GetSecureItemAggregateType<T extends SecureItemAggregateArgs> = {
      [P in keyof T & keyof AggregateSecureItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSecureItem[P]>
    : Prisma.GetScalarType<T[P], AggregateSecureItem[P]>
}




export type SecureItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SecureItemWhereInput
  orderBy?: Prisma.SecureItemOrderByWithAggregationInput | Prisma.SecureItemOrderByWithAggregationInput[]
  by: Prisma.SecureItemScalarFieldEnum[] | Prisma.SecureItemScalarFieldEnum
  having?: Prisma.SecureItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SecureItemCountAggregateInputType | true
  _min?: SecureItemMinAggregateInputType
  _max?: SecureItemMaxAggregateInputType
}

export type SecureItemGroupByOutputType = {
  id: string
  title: string
  category: string
  isCompromised: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt: Date
  updatedAt: Date
  lastScan: Date | null
  _count: SecureItemCountAggregateOutputType | null
  _min: SecureItemMinAggregateOutputType | null
  _max: SecureItemMaxAggregateOutputType | null
}

export type GetSecureItemGroupByPayload<T extends SecureItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SecureItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SecureItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SecureItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SecureItemGroupByOutputType[P]>
      }
    >
  >



export type SecureItemWhereInput = {
  AND?: Prisma.SecureItemWhereInput | Prisma.SecureItemWhereInput[]
  OR?: Prisma.SecureItemWhereInput[]
  NOT?: Prisma.SecureItemWhereInput | Prisma.SecureItemWhereInput[]
  id?: Prisma.StringFilter<"SecureItem"> | string
  title?: Prisma.StringFilter<"SecureItem"> | string
  category?: Prisma.StringFilter<"SecureItem"> | string
  isCompromised?: Prisma.BoolFilter<"SecureItem"> | boolean
  ciphertext?: Prisma.StringFilter<"SecureItem"> | string
  iv?: Prisma.StringFilter<"SecureItem"> | string
  tag?: Prisma.StringFilter<"SecureItem"> | string
  createdAt?: Prisma.DateTimeFilter<"SecureItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SecureItem"> | Date | string
  lastScan?: Prisma.DateTimeNullableFilter<"SecureItem"> | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsListRelationFilter
  accessors?: Prisma.ItemAccessListRelationFilter
}

export type SecureItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompromised?: Prisma.SortOrder
  ciphertext?: Prisma.SortOrder
  iv?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastScan?: Prisma.SortOrderInput | Prisma.SortOrder
  vaultItems?: Prisma.VaultSecureItemsOrderByRelationAggregateInput
  accessors?: Prisma.ItemAccessOrderByRelationAggregateInput
}

export type SecureItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SecureItemWhereInput | Prisma.SecureItemWhereInput[]
  OR?: Prisma.SecureItemWhereInput[]
  NOT?: Prisma.SecureItemWhereInput | Prisma.SecureItemWhereInput[]
  title?: Prisma.StringFilter<"SecureItem"> | string
  category?: Prisma.StringFilter<"SecureItem"> | string
  isCompromised?: Prisma.BoolFilter<"SecureItem"> | boolean
  ciphertext?: Prisma.StringFilter<"SecureItem"> | string
  iv?: Prisma.StringFilter<"SecureItem"> | string
  tag?: Prisma.StringFilter<"SecureItem"> | string
  createdAt?: Prisma.DateTimeFilter<"SecureItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SecureItem"> | Date | string
  lastScan?: Prisma.DateTimeNullableFilter<"SecureItem"> | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsListRelationFilter
  accessors?: Prisma.ItemAccessListRelationFilter
}, "id">

export type SecureItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompromised?: Prisma.SortOrder
  ciphertext?: Prisma.SortOrder
  iv?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastScan?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SecureItemCountOrderByAggregateInput
  _max?: Prisma.SecureItemMaxOrderByAggregateInput
  _min?: Prisma.SecureItemMinOrderByAggregateInput
}

export type SecureItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.SecureItemScalarWhereWithAggregatesInput | Prisma.SecureItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.SecureItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SecureItemScalarWhereWithAggregatesInput | Prisma.SecureItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  title?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  category?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  isCompromised?: Prisma.BoolWithAggregatesFilter<"SecureItem"> | boolean
  ciphertext?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  iv?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  tag?: Prisma.StringWithAggregatesFilter<"SecureItem"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SecureItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SecureItem"> | Date | string
  lastScan?: Prisma.DateTimeNullableWithAggregatesFilter<"SecureItem"> | Date | string | null
}

export type SecureItemCreateInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  vaultItems?: Prisma.VaultSecureItemsCreateNestedManyWithoutItemInput
  accessors?: Prisma.ItemAccessCreateNestedManyWithoutItemInput
}

export type SecureItemUncheckedCreateInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUncheckedCreateNestedManyWithoutItemInput
  accessors?: Prisma.ItemAccessUncheckedCreateNestedManyWithoutItemInput
}

export type SecureItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUpdateManyWithoutItemNestedInput
  accessors?: Prisma.ItemAccessUpdateManyWithoutItemNestedInput
}

export type SecureItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUncheckedUpdateManyWithoutItemNestedInput
  accessors?: Prisma.ItemAccessUncheckedUpdateManyWithoutItemNestedInput
}

export type SecureItemCreateManyInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
}

export type SecureItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SecureItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SecureItemScalarRelationFilter = {
  is?: Prisma.SecureItemWhereInput
  isNot?: Prisma.SecureItemWhereInput
}

export type SecureItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompromised?: Prisma.SortOrder
  ciphertext?: Prisma.SortOrder
  iv?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastScan?: Prisma.SortOrder
}

export type SecureItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompromised?: Prisma.SortOrder
  ciphertext?: Prisma.SortOrder
  iv?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastScan?: Prisma.SortOrder
}

export type SecureItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  category?: Prisma.SortOrder
  isCompromised?: Prisma.SortOrder
  ciphertext?: Prisma.SortOrder
  iv?: Prisma.SortOrder
  tag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  lastScan?: Prisma.SortOrder
}

export type SecureItemCreateNestedOneWithoutAccessorsInput = {
  create?: Prisma.XOR<Prisma.SecureItemCreateWithoutAccessorsInput, Prisma.SecureItemUncheckedCreateWithoutAccessorsInput>
  connectOrCreate?: Prisma.SecureItemCreateOrConnectWithoutAccessorsInput
  connect?: Prisma.SecureItemWhereUniqueInput
}

export type SecureItemUpdateOneRequiredWithoutAccessorsNestedInput = {
  create?: Prisma.XOR<Prisma.SecureItemCreateWithoutAccessorsInput, Prisma.SecureItemUncheckedCreateWithoutAccessorsInput>
  connectOrCreate?: Prisma.SecureItemCreateOrConnectWithoutAccessorsInput
  upsert?: Prisma.SecureItemUpsertWithoutAccessorsInput
  connect?: Prisma.SecureItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SecureItemUpdateToOneWithWhereWithoutAccessorsInput, Prisma.SecureItemUpdateWithoutAccessorsInput>, Prisma.SecureItemUncheckedUpdateWithoutAccessorsInput>
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type SecureItemCreateNestedOneWithoutVaultItemsInput = {
  create?: Prisma.XOR<Prisma.SecureItemCreateWithoutVaultItemsInput, Prisma.SecureItemUncheckedCreateWithoutVaultItemsInput>
  connectOrCreate?: Prisma.SecureItemCreateOrConnectWithoutVaultItemsInput
  connect?: Prisma.SecureItemWhereUniqueInput
}

export type SecureItemUpdateOneRequiredWithoutVaultItemsNestedInput = {
  create?: Prisma.XOR<Prisma.SecureItemCreateWithoutVaultItemsInput, Prisma.SecureItemUncheckedCreateWithoutVaultItemsInput>
  connectOrCreate?: Prisma.SecureItemCreateOrConnectWithoutVaultItemsInput
  upsert?: Prisma.SecureItemUpsertWithoutVaultItemsInput
  connect?: Prisma.SecureItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SecureItemUpdateToOneWithWhereWithoutVaultItemsInput, Prisma.SecureItemUpdateWithoutVaultItemsInput>, Prisma.SecureItemUncheckedUpdateWithoutVaultItemsInput>
}

export type SecureItemCreateWithoutAccessorsInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  vaultItems?: Prisma.VaultSecureItemsCreateNestedManyWithoutItemInput
}

export type SecureItemUncheckedCreateWithoutAccessorsInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUncheckedCreateNestedManyWithoutItemInput
}

export type SecureItemCreateOrConnectWithoutAccessorsInput = {
  where: Prisma.SecureItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SecureItemCreateWithoutAccessorsInput, Prisma.SecureItemUncheckedCreateWithoutAccessorsInput>
}

export type SecureItemUpsertWithoutAccessorsInput = {
  update: Prisma.XOR<Prisma.SecureItemUpdateWithoutAccessorsInput, Prisma.SecureItemUncheckedUpdateWithoutAccessorsInput>
  create: Prisma.XOR<Prisma.SecureItemCreateWithoutAccessorsInput, Prisma.SecureItemUncheckedCreateWithoutAccessorsInput>
  where?: Prisma.SecureItemWhereInput
}

export type SecureItemUpdateToOneWithWhereWithoutAccessorsInput = {
  where?: Prisma.SecureItemWhereInput
  data: Prisma.XOR<Prisma.SecureItemUpdateWithoutAccessorsInput, Prisma.SecureItemUncheckedUpdateWithoutAccessorsInput>
}

export type SecureItemUpdateWithoutAccessorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUpdateManyWithoutItemNestedInput
}

export type SecureItemUncheckedUpdateWithoutAccessorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  vaultItems?: Prisma.VaultSecureItemsUncheckedUpdateManyWithoutItemNestedInput
}

export type SecureItemCreateWithoutVaultItemsInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  accessors?: Prisma.ItemAccessCreateNestedManyWithoutItemInput
}

export type SecureItemUncheckedCreateWithoutVaultItemsInput = {
  id?: string
  title: string
  category: string
  isCompromised?: boolean
  ciphertext: string
  iv: string
  tag: string
  createdAt?: Date | string
  updatedAt?: Date | string
  lastScan?: Date | string | null
  accessors?: Prisma.ItemAccessUncheckedCreateNestedManyWithoutItemInput
}

export type SecureItemCreateOrConnectWithoutVaultItemsInput = {
  where: Prisma.SecureItemWhereUniqueInput
  create: Prisma.XOR<Prisma.SecureItemCreateWithoutVaultItemsInput, Prisma.SecureItemUncheckedCreateWithoutVaultItemsInput>
}

export type SecureItemUpsertWithoutVaultItemsInput = {
  update: Prisma.XOR<Prisma.SecureItemUpdateWithoutVaultItemsInput, Prisma.SecureItemUncheckedUpdateWithoutVaultItemsInput>
  create: Prisma.XOR<Prisma.SecureItemCreateWithoutVaultItemsInput, Prisma.SecureItemUncheckedCreateWithoutVaultItemsInput>
  where?: Prisma.SecureItemWhereInput
}

export type SecureItemUpdateToOneWithWhereWithoutVaultItemsInput = {
  where?: Prisma.SecureItemWhereInput
  data: Prisma.XOR<Prisma.SecureItemUpdateWithoutVaultItemsInput, Prisma.SecureItemUncheckedUpdateWithoutVaultItemsInput>
}

export type SecureItemUpdateWithoutVaultItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessors?: Prisma.ItemAccessUpdateManyWithoutItemNestedInput
}

export type SecureItemUncheckedUpdateWithoutVaultItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  isCompromised?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ciphertext?: Prisma.StringFieldUpdateOperationsInput | string
  iv?: Prisma.StringFieldUpdateOperationsInput | string
  tag?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastScan?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessors?: Prisma.ItemAccessUncheckedUpdateManyWithoutItemNestedInput
}


/**
 * Count Type SecureItemCountOutputType
 */

export type SecureItemCountOutputType = {
  vaultItems: number
  accessors: number
}

export type SecureItemCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vaultItems?: boolean | SecureItemCountOutputTypeCountVaultItemsArgs
  accessors?: boolean | SecureItemCountOutputTypeCountAccessorsArgs
}

/**
 * SecureItemCountOutputType without action
 */
export type SecureItemCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItemCountOutputType
   */
  select?: Prisma.SecureItemCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SecureItemCountOutputType without action
 */
export type SecureItemCountOutputTypeCountVaultItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VaultSecureItemsWhereInput
}

/**
 * SecureItemCountOutputType without action
 */
export type SecureItemCountOutputTypeCountAccessorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemAccessWhereInput
}


export type SecureItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  category?: boolean
  isCompromised?: boolean
  ciphertext?: boolean
  iv?: boolean
  tag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastScan?: boolean
  vaultItems?: boolean | Prisma.SecureItem$vaultItemsArgs<ExtArgs>
  accessors?: boolean | Prisma.SecureItem$accessorsArgs<ExtArgs>
  _count?: boolean | Prisma.SecureItemCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["secureItem"]>

export type SecureItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  category?: boolean
  isCompromised?: boolean
  ciphertext?: boolean
  iv?: boolean
  tag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastScan?: boolean
}, ExtArgs["result"]["secureItem"]>

export type SecureItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  category?: boolean
  isCompromised?: boolean
  ciphertext?: boolean
  iv?: boolean
  tag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastScan?: boolean
}, ExtArgs["result"]["secureItem"]>

export type SecureItemSelectScalar = {
  id?: boolean
  title?: boolean
  category?: boolean
  isCompromised?: boolean
  ciphertext?: boolean
  iv?: boolean
  tag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  lastScan?: boolean
}

export type SecureItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "category" | "isCompromised" | "ciphertext" | "iv" | "tag" | "createdAt" | "updatedAt" | "lastScan", ExtArgs["result"]["secureItem"]>
export type SecureItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vaultItems?: boolean | Prisma.SecureItem$vaultItemsArgs<ExtArgs>
  accessors?: boolean | Prisma.SecureItem$accessorsArgs<ExtArgs>
  _count?: boolean | Prisma.SecureItemCountOutputTypeDefaultArgs<ExtArgs>
}
export type SecureItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SecureItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SecureItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SecureItem"
  objects: {
    vaultItems: Prisma.$VaultSecureItemsPayload<ExtArgs>[]
    accessors: Prisma.$ItemAccessPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    category: string
    isCompromised: boolean
    ciphertext: string
    iv: string
    tag: string
    createdAt: Date
    updatedAt: Date
    lastScan: Date | null
  }, ExtArgs["result"]["secureItem"]>
  composites: {}
}

export type SecureItemGetPayload<S extends boolean | null | undefined | SecureItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SecureItemPayload, S>

export type SecureItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SecureItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SecureItemCountAggregateInputType | true
  }

export interface SecureItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SecureItem'], meta: { name: 'SecureItem' } }
  /**
   * Find zero or one SecureItem that matches the filter.
   * @param {SecureItemFindUniqueArgs} args - Arguments to find a SecureItem
   * @example
   * // Get one SecureItem
   * const secureItem = await prisma.secureItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SecureItemFindUniqueArgs>(args: Prisma.SelectSubset<T, SecureItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SecureItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SecureItemFindUniqueOrThrowArgs} args - Arguments to find a SecureItem
   * @example
   * // Get one SecureItem
   * const secureItem = await prisma.secureItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SecureItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SecureItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SecureItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemFindFirstArgs} args - Arguments to find a SecureItem
   * @example
   * // Get one SecureItem
   * const secureItem = await prisma.secureItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SecureItemFindFirstArgs>(args?: Prisma.SelectSubset<T, SecureItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SecureItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemFindFirstOrThrowArgs} args - Arguments to find a SecureItem
   * @example
   * // Get one SecureItem
   * const secureItem = await prisma.secureItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SecureItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SecureItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SecureItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SecureItems
   * const secureItems = await prisma.secureItem.findMany()
   * 
   * // Get first 10 SecureItems
   * const secureItems = await prisma.secureItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const secureItemWithIdOnly = await prisma.secureItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SecureItemFindManyArgs>(args?: Prisma.SelectSubset<T, SecureItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SecureItem.
   * @param {SecureItemCreateArgs} args - Arguments to create a SecureItem.
   * @example
   * // Create one SecureItem
   * const SecureItem = await prisma.secureItem.create({
   *   data: {
   *     // ... data to create a SecureItem
   *   }
   * })
   * 
   */
  create<T extends SecureItemCreateArgs>(args: Prisma.SelectSubset<T, SecureItemCreateArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SecureItems.
   * @param {SecureItemCreateManyArgs} args - Arguments to create many SecureItems.
   * @example
   * // Create many SecureItems
   * const secureItem = await prisma.secureItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SecureItemCreateManyArgs>(args?: Prisma.SelectSubset<T, SecureItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SecureItems and returns the data saved in the database.
   * @param {SecureItemCreateManyAndReturnArgs} args - Arguments to create many SecureItems.
   * @example
   * // Create many SecureItems
   * const secureItem = await prisma.secureItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SecureItems and only return the `id`
   * const secureItemWithIdOnly = await prisma.secureItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SecureItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SecureItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SecureItem.
   * @param {SecureItemDeleteArgs} args - Arguments to delete one SecureItem.
   * @example
   * // Delete one SecureItem
   * const SecureItem = await prisma.secureItem.delete({
   *   where: {
   *     // ... filter to delete one SecureItem
   *   }
   * })
   * 
   */
  delete<T extends SecureItemDeleteArgs>(args: Prisma.SelectSubset<T, SecureItemDeleteArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SecureItem.
   * @param {SecureItemUpdateArgs} args - Arguments to update one SecureItem.
   * @example
   * // Update one SecureItem
   * const secureItem = await prisma.secureItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SecureItemUpdateArgs>(args: Prisma.SelectSubset<T, SecureItemUpdateArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SecureItems.
   * @param {SecureItemDeleteManyArgs} args - Arguments to filter SecureItems to delete.
   * @example
   * // Delete a few SecureItems
   * const { count } = await prisma.secureItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SecureItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, SecureItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SecureItems
   * const secureItem = await prisma.secureItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SecureItemUpdateManyArgs>(args: Prisma.SelectSubset<T, SecureItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SecureItems and returns the data updated in the database.
   * @param {SecureItemUpdateManyAndReturnArgs} args - Arguments to update many SecureItems.
   * @example
   * // Update many SecureItems
   * const secureItem = await prisma.secureItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SecureItems and only return the `id`
   * const secureItemWithIdOnly = await prisma.secureItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SecureItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SecureItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SecureItem.
   * @param {SecureItemUpsertArgs} args - Arguments to update or create a SecureItem.
   * @example
   * // Update or create a SecureItem
   * const secureItem = await prisma.secureItem.upsert({
   *   create: {
   *     // ... data to create a SecureItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SecureItem we want to update
   *   }
   * })
   */
  upsert<T extends SecureItemUpsertArgs>(args: Prisma.SelectSubset<T, SecureItemUpsertArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemCountArgs} args - Arguments to filter SecureItems to count.
   * @example
   * // Count the number of SecureItems
   * const count = await prisma.secureItem.count({
   *   where: {
   *     // ... the filter for the SecureItems we want to count
   *   }
   * })
  **/
  count<T extends SecureItemCountArgs>(
    args?: Prisma.Subset<T, SecureItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SecureItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SecureItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SecureItemAggregateArgs>(args: Prisma.Subset<T, SecureItemAggregateArgs>): Prisma.PrismaPromise<GetSecureItemAggregateType<T>>

  /**
   * Group by SecureItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecureItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SecureItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SecureItemGroupByArgs['orderBy'] }
      : { orderBy?: SecureItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SecureItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSecureItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SecureItem model
 */
readonly fields: SecureItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SecureItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SecureItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  vaultItems<T extends Prisma.SecureItem$vaultItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SecureItem$vaultItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  accessors<T extends Prisma.SecureItem$accessorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SecureItem$accessorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemAccessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SecureItem model
 */
export interface SecureItemFieldRefs {
  readonly id: Prisma.FieldRef<"SecureItem", 'String'>
  readonly title: Prisma.FieldRef<"SecureItem", 'String'>
  readonly category: Prisma.FieldRef<"SecureItem", 'String'>
  readonly isCompromised: Prisma.FieldRef<"SecureItem", 'Boolean'>
  readonly ciphertext: Prisma.FieldRef<"SecureItem", 'String'>
  readonly iv: Prisma.FieldRef<"SecureItem", 'String'>
  readonly tag: Prisma.FieldRef<"SecureItem", 'String'>
  readonly createdAt: Prisma.FieldRef<"SecureItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SecureItem", 'DateTime'>
  readonly lastScan: Prisma.FieldRef<"SecureItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SecureItem findUnique
 */
export type SecureItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter, which SecureItem to fetch.
   */
  where: Prisma.SecureItemWhereUniqueInput
}

/**
 * SecureItem findUniqueOrThrow
 */
export type SecureItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter, which SecureItem to fetch.
   */
  where: Prisma.SecureItemWhereUniqueInput
}

/**
 * SecureItem findFirst
 */
export type SecureItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter, which SecureItem to fetch.
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SecureItems to fetch.
   */
  orderBy?: Prisma.SecureItemOrderByWithRelationInput | Prisma.SecureItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SecureItems.
   */
  cursor?: Prisma.SecureItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SecureItems.
   */
  distinct?: Prisma.SecureItemScalarFieldEnum | Prisma.SecureItemScalarFieldEnum[]
}

/**
 * SecureItem findFirstOrThrow
 */
export type SecureItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter, which SecureItem to fetch.
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SecureItems to fetch.
   */
  orderBy?: Prisma.SecureItemOrderByWithRelationInput | Prisma.SecureItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SecureItems.
   */
  cursor?: Prisma.SecureItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SecureItems.
   */
  distinct?: Prisma.SecureItemScalarFieldEnum | Prisma.SecureItemScalarFieldEnum[]
}

/**
 * SecureItem findMany
 */
export type SecureItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter, which SecureItems to fetch.
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SecureItems to fetch.
   */
  orderBy?: Prisma.SecureItemOrderByWithRelationInput | Prisma.SecureItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SecureItems.
   */
  cursor?: Prisma.SecureItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SecureItems.
   */
  distinct?: Prisma.SecureItemScalarFieldEnum | Prisma.SecureItemScalarFieldEnum[]
}

/**
 * SecureItem create
 */
export type SecureItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * The data needed to create a SecureItem.
   */
  data: Prisma.XOR<Prisma.SecureItemCreateInput, Prisma.SecureItemUncheckedCreateInput>
}

/**
 * SecureItem createMany
 */
export type SecureItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SecureItems.
   */
  data: Prisma.SecureItemCreateManyInput | Prisma.SecureItemCreateManyInput[]
}

/**
 * SecureItem createManyAndReturn
 */
export type SecureItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * The data used to create many SecureItems.
   */
  data: Prisma.SecureItemCreateManyInput | Prisma.SecureItemCreateManyInput[]
}

/**
 * SecureItem update
 */
export type SecureItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * The data needed to update a SecureItem.
   */
  data: Prisma.XOR<Prisma.SecureItemUpdateInput, Prisma.SecureItemUncheckedUpdateInput>
  /**
   * Choose, which SecureItem to update.
   */
  where: Prisma.SecureItemWhereUniqueInput
}

/**
 * SecureItem updateMany
 */
export type SecureItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SecureItems.
   */
  data: Prisma.XOR<Prisma.SecureItemUpdateManyMutationInput, Prisma.SecureItemUncheckedUpdateManyInput>
  /**
   * Filter which SecureItems to update
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * Limit how many SecureItems to update.
   */
  limit?: number
}

/**
 * SecureItem updateManyAndReturn
 */
export type SecureItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * The data used to update SecureItems.
   */
  data: Prisma.XOR<Prisma.SecureItemUpdateManyMutationInput, Prisma.SecureItemUncheckedUpdateManyInput>
  /**
   * Filter which SecureItems to update
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * Limit how many SecureItems to update.
   */
  limit?: number
}

/**
 * SecureItem upsert
 */
export type SecureItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * The filter to search for the SecureItem to update in case it exists.
   */
  where: Prisma.SecureItemWhereUniqueInput
  /**
   * In case the SecureItem found by the `where` argument doesn't exist, create a new SecureItem with this data.
   */
  create: Prisma.XOR<Prisma.SecureItemCreateInput, Prisma.SecureItemUncheckedCreateInput>
  /**
   * In case the SecureItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SecureItemUpdateInput, Prisma.SecureItemUncheckedUpdateInput>
}

/**
 * SecureItem delete
 */
export type SecureItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
  /**
   * Filter which SecureItem to delete.
   */
  where: Prisma.SecureItemWhereUniqueInput
}

/**
 * SecureItem deleteMany
 */
export type SecureItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SecureItems to delete
   */
  where?: Prisma.SecureItemWhereInput
  /**
   * Limit how many SecureItems to delete.
   */
  limit?: number
}

/**
 * SecureItem.vaultItems
 */
export type SecureItem$vaultItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  where?: Prisma.VaultSecureItemsWhereInput
  orderBy?: Prisma.VaultSecureItemsOrderByWithRelationInput | Prisma.VaultSecureItemsOrderByWithRelationInput[]
  cursor?: Prisma.VaultSecureItemsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VaultSecureItemsScalarFieldEnum | Prisma.VaultSecureItemsScalarFieldEnum[]
}

/**
 * SecureItem.accessors
 */
export type SecureItem$accessorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemAccess
   */
  select?: Prisma.ItemAccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemAccess
   */
  omit?: Prisma.ItemAccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemAccessInclude<ExtArgs> | null
  where?: Prisma.ItemAccessWhereInput
  orderBy?: Prisma.ItemAccessOrderByWithRelationInput | Prisma.ItemAccessOrderByWithRelationInput[]
  cursor?: Prisma.ItemAccessWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ItemAccessScalarFieldEnum | Prisma.ItemAccessScalarFieldEnum[]
}

/**
 * SecureItem without action
 */
export type SecureItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SecureItem
   */
  select?: Prisma.SecureItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SecureItem
   */
  omit?: Prisma.SecureItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SecureItemInclude<ExtArgs> | null
}
