
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VaultSecureItems` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VaultSecureItems
 * 
 */
export type VaultSecureItemsModel = runtime.Types.Result.DefaultSelection<Prisma.$VaultSecureItemsPayload>

export type AggregateVaultSecureItems = {
  _count: VaultSecureItemsCountAggregateOutputType | null
  _min: VaultSecureItemsMinAggregateOutputType | null
  _max: VaultSecureItemsMaxAggregateOutputType | null
}

export type VaultSecureItemsMinAggregateOutputType = {
  vaultId: string | null
  itemId: string | null
}

export type VaultSecureItemsMaxAggregateOutputType = {
  vaultId: string | null
  itemId: string | null
}

export type VaultSecureItemsCountAggregateOutputType = {
  vaultId: number
  itemId: number
  _all: number
}


export type VaultSecureItemsMinAggregateInputType = {
  vaultId?: true
  itemId?: true
}

export type VaultSecureItemsMaxAggregateInputType = {
  vaultId?: true
  itemId?: true
}

export type VaultSecureItemsCountAggregateInputType = {
  vaultId?: true
  itemId?: true
  _all?: true
}

export type VaultSecureItemsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VaultSecureItems to aggregate.
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VaultSecureItems to fetch.
   */
  orderBy?: Prisma.VaultSecureItemsOrderByWithRelationInput | Prisma.VaultSecureItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VaultSecureItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VaultSecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VaultSecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VaultSecureItems
  **/
  _count?: true | VaultSecureItemsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VaultSecureItemsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VaultSecureItemsMaxAggregateInputType
}

export type GetVaultSecureItemsAggregateType<T extends VaultSecureItemsAggregateArgs> = {
      [P in keyof T & keyof AggregateVaultSecureItems]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVaultSecureItems[P]>
    : Prisma.GetScalarType<T[P], AggregateVaultSecureItems[P]>
}




export type VaultSecureItemsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VaultSecureItemsWhereInput
  orderBy?: Prisma.VaultSecureItemsOrderByWithAggregationInput | Prisma.VaultSecureItemsOrderByWithAggregationInput[]
  by: Prisma.VaultSecureItemsScalarFieldEnum[] | Prisma.VaultSecureItemsScalarFieldEnum
  having?: Prisma.VaultSecureItemsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VaultSecureItemsCountAggregateInputType | true
  _min?: VaultSecureItemsMinAggregateInputType
  _max?: VaultSecureItemsMaxAggregateInputType
}

export type VaultSecureItemsGroupByOutputType = {
  vaultId: string
  itemId: string
  _count: VaultSecureItemsCountAggregateOutputType | null
  _min: VaultSecureItemsMinAggregateOutputType | null
  _max: VaultSecureItemsMaxAggregateOutputType | null
}

export type GetVaultSecureItemsGroupByPayload<T extends VaultSecureItemsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VaultSecureItemsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VaultSecureItemsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VaultSecureItemsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VaultSecureItemsGroupByOutputType[P]>
      }
    >
  >



export type VaultSecureItemsWhereInput = {
  AND?: Prisma.VaultSecureItemsWhereInput | Prisma.VaultSecureItemsWhereInput[]
  OR?: Prisma.VaultSecureItemsWhereInput[]
  NOT?: Prisma.VaultSecureItemsWhereInput | Prisma.VaultSecureItemsWhereInput[]
  vaultId?: Prisma.StringFilter<"VaultSecureItems"> | string
  itemId?: Prisma.StringFilter<"VaultSecureItems"> | string
  item?: Prisma.XOR<Prisma.SecureItemScalarRelationFilter, Prisma.SecureItemWhereInput>
  vault?: Prisma.XOR<Prisma.VaultScalarRelationFilter, Prisma.VaultWhereInput>
}

export type VaultSecureItemsOrderByWithRelationInput = {
  vaultId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  item?: Prisma.SecureItemOrderByWithRelationInput
  vault?: Prisma.VaultOrderByWithRelationInput
}

export type VaultSecureItemsWhereUniqueInput = Prisma.AtLeast<{
  vaultId_itemId?: Prisma.VaultSecureItemsVaultIdItemIdCompoundUniqueInput
  AND?: Prisma.VaultSecureItemsWhereInput | Prisma.VaultSecureItemsWhereInput[]
  OR?: Prisma.VaultSecureItemsWhereInput[]
  NOT?: Prisma.VaultSecureItemsWhereInput | Prisma.VaultSecureItemsWhereInput[]
  vaultId?: Prisma.StringFilter<"VaultSecureItems"> | string
  itemId?: Prisma.StringFilter<"VaultSecureItems"> | string
  item?: Prisma.XOR<Prisma.SecureItemScalarRelationFilter, Prisma.SecureItemWhereInput>
  vault?: Prisma.XOR<Prisma.VaultScalarRelationFilter, Prisma.VaultWhereInput>
}, "vaultId_itemId">

export type VaultSecureItemsOrderByWithAggregationInput = {
  vaultId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  _count?: Prisma.VaultSecureItemsCountOrderByAggregateInput
  _max?: Prisma.VaultSecureItemsMaxOrderByAggregateInput
  _min?: Prisma.VaultSecureItemsMinOrderByAggregateInput
}

export type VaultSecureItemsScalarWhereWithAggregatesInput = {
  AND?: Prisma.VaultSecureItemsScalarWhereWithAggregatesInput | Prisma.VaultSecureItemsScalarWhereWithAggregatesInput[]
  OR?: Prisma.VaultSecureItemsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VaultSecureItemsScalarWhereWithAggregatesInput | Prisma.VaultSecureItemsScalarWhereWithAggregatesInput[]
  vaultId?: Prisma.StringWithAggregatesFilter<"VaultSecureItems"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"VaultSecureItems"> | string
}

export type VaultSecureItemsCreateInput = {
  item: Prisma.SecureItemCreateNestedOneWithoutVaultItemsInput
  vault: Prisma.VaultCreateNestedOneWithoutVaultItemsInput
}

export type VaultSecureItemsUncheckedCreateInput = {
  vaultId: string
  itemId: string
}

export type VaultSecureItemsUpdateInput = {
  item?: Prisma.SecureItemUpdateOneRequiredWithoutVaultItemsNestedInput
  vault?: Prisma.VaultUpdateOneRequiredWithoutVaultItemsNestedInput
}

export type VaultSecureItemsUncheckedUpdateInput = {
  vaultId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VaultSecureItemsCreateManyInput = {
  vaultId: string
  itemId: string
}

export type VaultSecureItemsUpdateManyMutationInput = {

}

export type VaultSecureItemsUncheckedUpdateManyInput = {
  vaultId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VaultSecureItemsListRelationFilter = {
  every?: Prisma.VaultSecureItemsWhereInput
  some?: Prisma.VaultSecureItemsWhereInput
  none?: Prisma.VaultSecureItemsWhereInput
}

export type VaultSecureItemsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VaultSecureItemsVaultIdItemIdCompoundUniqueInput = {
  vaultId: string
  itemId: string
}

export type VaultSecureItemsCountOrderByAggregateInput = {
  vaultId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type VaultSecureItemsMaxOrderByAggregateInput = {
  vaultId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type VaultSecureItemsMinOrderByAggregateInput = {
  vaultId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
}

export type VaultSecureItemsCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput> | Prisma.VaultSecureItemsCreateWithoutItemInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput | Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyItemInputEnvelope
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
}

export type VaultSecureItemsUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput> | Prisma.VaultSecureItemsCreateWithoutItemInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput | Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyItemInputEnvelope
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
}

export type VaultSecureItemsUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput> | Prisma.VaultSecureItemsCreateWithoutItemInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput | Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutItemInput | Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyItemInputEnvelope
  set?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  disconnect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  delete?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  update?: Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutItemInput | Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.VaultSecureItemsUpdateManyWithWhereWithoutItemInput | Prisma.VaultSecureItemsUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
}

export type VaultSecureItemsUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput> | Prisma.VaultSecureItemsCreateWithoutItemInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput | Prisma.VaultSecureItemsCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutItemInput | Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyItemInputEnvelope
  set?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  disconnect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  delete?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  update?: Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutItemInput | Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.VaultSecureItemsUpdateManyWithWhereWithoutItemInput | Prisma.VaultSecureItemsUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
}

export type VaultSecureItemsCreateNestedManyWithoutVaultInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput> | Prisma.VaultSecureItemsCreateWithoutVaultInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput | Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyVaultInputEnvelope
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
}

export type VaultSecureItemsUncheckedCreateNestedManyWithoutVaultInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput> | Prisma.VaultSecureItemsCreateWithoutVaultInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput | Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyVaultInputEnvelope
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
}

export type VaultSecureItemsUpdateManyWithoutVaultNestedInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput> | Prisma.VaultSecureItemsCreateWithoutVaultInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput | Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput[]
  upsert?: Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutVaultInput | Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutVaultInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyVaultInputEnvelope
  set?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  disconnect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  delete?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  update?: Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutVaultInput | Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutVaultInput[]
  updateMany?: Prisma.VaultSecureItemsUpdateManyWithWhereWithoutVaultInput | Prisma.VaultSecureItemsUpdateManyWithWhereWithoutVaultInput[]
  deleteMany?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
}

export type VaultSecureItemsUncheckedUpdateManyWithoutVaultNestedInput = {
  create?: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput> | Prisma.VaultSecureItemsCreateWithoutVaultInput[] | Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput[]
  connectOrCreate?: Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput | Prisma.VaultSecureItemsCreateOrConnectWithoutVaultInput[]
  upsert?: Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutVaultInput | Prisma.VaultSecureItemsUpsertWithWhereUniqueWithoutVaultInput[]
  createMany?: Prisma.VaultSecureItemsCreateManyVaultInputEnvelope
  set?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  disconnect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  delete?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  connect?: Prisma.VaultSecureItemsWhereUniqueInput | Prisma.VaultSecureItemsWhereUniqueInput[]
  update?: Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutVaultInput | Prisma.VaultSecureItemsUpdateWithWhereUniqueWithoutVaultInput[]
  updateMany?: Prisma.VaultSecureItemsUpdateManyWithWhereWithoutVaultInput | Prisma.VaultSecureItemsUpdateManyWithWhereWithoutVaultInput[]
  deleteMany?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
}

export type VaultSecureItemsCreateWithoutItemInput = {
  vault: Prisma.VaultCreateNestedOneWithoutVaultItemsInput
}

export type VaultSecureItemsUncheckedCreateWithoutItemInput = {
  vaultId: string
}

export type VaultSecureItemsCreateOrConnectWithoutItemInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput>
}

export type VaultSecureItemsCreateManyItemInputEnvelope = {
  data: Prisma.VaultSecureItemsCreateManyItemInput | Prisma.VaultSecureItemsCreateManyItemInput[]
}

export type VaultSecureItemsUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.VaultSecureItemsUpdateWithoutItemInput, Prisma.VaultSecureItemsUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutItemInput, Prisma.VaultSecureItemsUncheckedCreateWithoutItemInput>
}

export type VaultSecureItemsUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateWithoutItemInput, Prisma.VaultSecureItemsUncheckedUpdateWithoutItemInput>
}

export type VaultSecureItemsUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.VaultSecureItemsScalarWhereInput
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateManyMutationInput, Prisma.VaultSecureItemsUncheckedUpdateManyWithoutItemInput>
}

export type VaultSecureItemsScalarWhereInput = {
  AND?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
  OR?: Prisma.VaultSecureItemsScalarWhereInput[]
  NOT?: Prisma.VaultSecureItemsScalarWhereInput | Prisma.VaultSecureItemsScalarWhereInput[]
  vaultId?: Prisma.StringFilter<"VaultSecureItems"> | string
  itemId?: Prisma.StringFilter<"VaultSecureItems"> | string
}

export type VaultSecureItemsCreateWithoutVaultInput = {
  item: Prisma.SecureItemCreateNestedOneWithoutVaultItemsInput
}

export type VaultSecureItemsUncheckedCreateWithoutVaultInput = {
  itemId: string
}

export type VaultSecureItemsCreateOrConnectWithoutVaultInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  create: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput>
}

export type VaultSecureItemsCreateManyVaultInputEnvelope = {
  data: Prisma.VaultSecureItemsCreateManyVaultInput | Prisma.VaultSecureItemsCreateManyVaultInput[]
}

export type VaultSecureItemsUpsertWithWhereUniqueWithoutVaultInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  update: Prisma.XOR<Prisma.VaultSecureItemsUpdateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedUpdateWithoutVaultInput>
  create: Prisma.XOR<Prisma.VaultSecureItemsCreateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedCreateWithoutVaultInput>
}

export type VaultSecureItemsUpdateWithWhereUniqueWithoutVaultInput = {
  where: Prisma.VaultSecureItemsWhereUniqueInput
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateWithoutVaultInput, Prisma.VaultSecureItemsUncheckedUpdateWithoutVaultInput>
}

export type VaultSecureItemsUpdateManyWithWhereWithoutVaultInput = {
  where: Prisma.VaultSecureItemsScalarWhereInput
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateManyMutationInput, Prisma.VaultSecureItemsUncheckedUpdateManyWithoutVaultInput>
}

export type VaultSecureItemsCreateManyItemInput = {
  vaultId: string
}

export type VaultSecureItemsUpdateWithoutItemInput = {
  vault?: Prisma.VaultUpdateOneRequiredWithoutVaultItemsNestedInput
}

export type VaultSecureItemsUncheckedUpdateWithoutItemInput = {
  vaultId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VaultSecureItemsUncheckedUpdateManyWithoutItemInput = {
  vaultId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VaultSecureItemsCreateManyVaultInput = {
  itemId: string
}

export type VaultSecureItemsUpdateWithoutVaultInput = {
  item?: Prisma.SecureItemUpdateOneRequiredWithoutVaultItemsNestedInput
}

export type VaultSecureItemsUncheckedUpdateWithoutVaultInput = {
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VaultSecureItemsUncheckedUpdateManyWithoutVaultInput = {
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type VaultSecureItemsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  vaultId?: boolean
  itemId?: boolean
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vaultSecureItems"]>

export type VaultSecureItemsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  vaultId?: boolean
  itemId?: boolean
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vaultSecureItems"]>

export type VaultSecureItemsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  vaultId?: boolean
  itemId?: boolean
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vaultSecureItems"]>

export type VaultSecureItemsSelectScalar = {
  vaultId?: boolean
  itemId?: boolean
}

export type VaultSecureItemsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"vaultId" | "itemId", ExtArgs["result"]["vaultSecureItems"]>
export type VaultSecureItemsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}
export type VaultSecureItemsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}
export type VaultSecureItemsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.SecureItemDefaultArgs<ExtArgs>
  vault?: boolean | Prisma.VaultDefaultArgs<ExtArgs>
}

export type $VaultSecureItemsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VaultSecureItems"
  objects: {
    item: Prisma.$SecureItemPayload<ExtArgs>
    vault: Prisma.$VaultPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    vaultId: string
    itemId: string
  }, ExtArgs["result"]["vaultSecureItems"]>
  composites: {}
}

export type VaultSecureItemsGetPayload<S extends boolean | null | undefined | VaultSecureItemsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload, S>

export type VaultSecureItemsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VaultSecureItemsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VaultSecureItemsCountAggregateInputType | true
  }

export interface VaultSecureItemsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VaultSecureItems'], meta: { name: 'VaultSecureItems' } }
  /**
   * Find zero or one VaultSecureItems that matches the filter.
   * @param {VaultSecureItemsFindUniqueArgs} args - Arguments to find a VaultSecureItems
   * @example
   * // Get one VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VaultSecureItemsFindUniqueArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VaultSecureItems that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VaultSecureItemsFindUniqueOrThrowArgs} args - Arguments to find a VaultSecureItems
   * @example
   * // Get one VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VaultSecureItemsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VaultSecureItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsFindFirstArgs} args - Arguments to find a VaultSecureItems
   * @example
   * // Get one VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VaultSecureItemsFindFirstArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsFindFirstArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VaultSecureItems that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsFindFirstOrThrowArgs} args - Arguments to find a VaultSecureItems
   * @example
   * // Get one VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VaultSecureItemsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VaultSecureItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findMany()
   * 
   * // Get first 10 VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.findMany({ take: 10 })
   * 
   * // Only select the `vaultId`
   * const vaultSecureItemsWithVaultIdOnly = await prisma.vaultSecureItems.findMany({ select: { vaultId: true } })
   * 
   */
  findMany<T extends VaultSecureItemsFindManyArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VaultSecureItems.
   * @param {VaultSecureItemsCreateArgs} args - Arguments to create a VaultSecureItems.
   * @example
   * // Create one VaultSecureItems
   * const VaultSecureItems = await prisma.vaultSecureItems.create({
   *   data: {
   *     // ... data to create a VaultSecureItems
   *   }
   * })
   * 
   */
  create<T extends VaultSecureItemsCreateArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsCreateArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VaultSecureItems.
   * @param {VaultSecureItemsCreateManyArgs} args - Arguments to create many VaultSecureItems.
   * @example
   * // Create many VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VaultSecureItemsCreateManyArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VaultSecureItems and returns the data saved in the database.
   * @param {VaultSecureItemsCreateManyAndReturnArgs} args - Arguments to create many VaultSecureItems.
   * @example
   * // Create many VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VaultSecureItems and only return the `vaultId`
   * const vaultSecureItemsWithVaultIdOnly = await prisma.vaultSecureItems.createManyAndReturn({
   *   select: { vaultId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VaultSecureItemsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VaultSecureItems.
   * @param {VaultSecureItemsDeleteArgs} args - Arguments to delete one VaultSecureItems.
   * @example
   * // Delete one VaultSecureItems
   * const VaultSecureItems = await prisma.vaultSecureItems.delete({
   *   where: {
   *     // ... filter to delete one VaultSecureItems
   *   }
   * })
   * 
   */
  delete<T extends VaultSecureItemsDeleteArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsDeleteArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VaultSecureItems.
   * @param {VaultSecureItemsUpdateArgs} args - Arguments to update one VaultSecureItems.
   * @example
   * // Update one VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VaultSecureItemsUpdateArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsUpdateArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VaultSecureItems.
   * @param {VaultSecureItemsDeleteManyArgs} args - Arguments to filter VaultSecureItems to delete.
   * @example
   * // Delete a few VaultSecureItems
   * const { count } = await prisma.vaultSecureItems.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VaultSecureItemsDeleteManyArgs>(args?: Prisma.SelectSubset<T, VaultSecureItemsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VaultSecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VaultSecureItemsUpdateManyArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VaultSecureItems and returns the data updated in the database.
   * @param {VaultSecureItemsUpdateManyAndReturnArgs} args - Arguments to update many VaultSecureItems.
   * @example
   * // Update many VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VaultSecureItems and only return the `vaultId`
   * const vaultSecureItemsWithVaultIdOnly = await prisma.vaultSecureItems.updateManyAndReturn({
   *   select: { vaultId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VaultSecureItemsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VaultSecureItems.
   * @param {VaultSecureItemsUpsertArgs} args - Arguments to update or create a VaultSecureItems.
   * @example
   * // Update or create a VaultSecureItems
   * const vaultSecureItems = await prisma.vaultSecureItems.upsert({
   *   create: {
   *     // ... data to create a VaultSecureItems
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VaultSecureItems we want to update
   *   }
   * })
   */
  upsert<T extends VaultSecureItemsUpsertArgs>(args: Prisma.SelectSubset<T, VaultSecureItemsUpsertArgs<ExtArgs>>): Prisma.Prisma__VaultSecureItemsClient<runtime.Types.Result.GetResult<Prisma.$VaultSecureItemsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VaultSecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsCountArgs} args - Arguments to filter VaultSecureItems to count.
   * @example
   * // Count the number of VaultSecureItems
   * const count = await prisma.vaultSecureItems.count({
   *   where: {
   *     // ... the filter for the VaultSecureItems we want to count
   *   }
   * })
  **/
  count<T extends VaultSecureItemsCountArgs>(
    args?: Prisma.Subset<T, VaultSecureItemsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VaultSecureItemsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VaultSecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VaultSecureItemsAggregateArgs>(args: Prisma.Subset<T, VaultSecureItemsAggregateArgs>): Prisma.PrismaPromise<GetVaultSecureItemsAggregateType<T>>

  /**
   * Group by VaultSecureItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VaultSecureItemsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VaultSecureItemsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VaultSecureItemsGroupByArgs['orderBy'] }
      : { orderBy?: VaultSecureItemsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VaultSecureItemsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVaultSecureItemsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VaultSecureItems model
 */
readonly fields: VaultSecureItemsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VaultSecureItems.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VaultSecureItemsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  item<T extends Prisma.SecureItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SecureItemDefaultArgs<ExtArgs>>): Prisma.Prisma__SecureItemClient<runtime.Types.Result.GetResult<Prisma.$SecureItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  vault<T extends Prisma.VaultDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VaultDefaultArgs<ExtArgs>>): Prisma.Prisma__VaultClient<runtime.Types.Result.GetResult<Prisma.$VaultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VaultSecureItems model
 */
export interface VaultSecureItemsFieldRefs {
  readonly vaultId: Prisma.FieldRef<"VaultSecureItems", 'String'>
  readonly itemId: Prisma.FieldRef<"VaultSecureItems", 'String'>
}
    

// Custom InputTypes
/**
 * VaultSecureItems findUnique
 */
export type VaultSecureItemsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter, which VaultSecureItems to fetch.
   */
  where: Prisma.VaultSecureItemsWhereUniqueInput
}

/**
 * VaultSecureItems findUniqueOrThrow
 */
export type VaultSecureItemsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter, which VaultSecureItems to fetch.
   */
  where: Prisma.VaultSecureItemsWhereUniqueInput
}

/**
 * VaultSecureItems findFirst
 */
export type VaultSecureItemsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter, which VaultSecureItems to fetch.
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VaultSecureItems to fetch.
   */
  orderBy?: Prisma.VaultSecureItemsOrderByWithRelationInput | Prisma.VaultSecureItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VaultSecureItems.
   */
  cursor?: Prisma.VaultSecureItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VaultSecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VaultSecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VaultSecureItems.
   */
  distinct?: Prisma.VaultSecureItemsScalarFieldEnum | Prisma.VaultSecureItemsScalarFieldEnum[]
}

/**
 * VaultSecureItems findFirstOrThrow
 */
export type VaultSecureItemsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter, which VaultSecureItems to fetch.
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VaultSecureItems to fetch.
   */
  orderBy?: Prisma.VaultSecureItemsOrderByWithRelationInput | Prisma.VaultSecureItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VaultSecureItems.
   */
  cursor?: Prisma.VaultSecureItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VaultSecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VaultSecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VaultSecureItems.
   */
  distinct?: Prisma.VaultSecureItemsScalarFieldEnum | Prisma.VaultSecureItemsScalarFieldEnum[]
}

/**
 * VaultSecureItems findMany
 */
export type VaultSecureItemsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter, which VaultSecureItems to fetch.
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VaultSecureItems to fetch.
   */
  orderBy?: Prisma.VaultSecureItemsOrderByWithRelationInput | Prisma.VaultSecureItemsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VaultSecureItems.
   */
  cursor?: Prisma.VaultSecureItemsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VaultSecureItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VaultSecureItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VaultSecureItems.
   */
  distinct?: Prisma.VaultSecureItemsScalarFieldEnum | Prisma.VaultSecureItemsScalarFieldEnum[]
}

/**
 * VaultSecureItems create
 */
export type VaultSecureItemsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * The data needed to create a VaultSecureItems.
   */
  data: Prisma.XOR<Prisma.VaultSecureItemsCreateInput, Prisma.VaultSecureItemsUncheckedCreateInput>
}

/**
 * VaultSecureItems createMany
 */
export type VaultSecureItemsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VaultSecureItems.
   */
  data: Prisma.VaultSecureItemsCreateManyInput | Prisma.VaultSecureItemsCreateManyInput[]
}

/**
 * VaultSecureItems createManyAndReturn
 */
export type VaultSecureItemsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * The data used to create many VaultSecureItems.
   */
  data: Prisma.VaultSecureItemsCreateManyInput | Prisma.VaultSecureItemsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VaultSecureItems update
 */
export type VaultSecureItemsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * The data needed to update a VaultSecureItems.
   */
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateInput, Prisma.VaultSecureItemsUncheckedUpdateInput>
  /**
   * Choose, which VaultSecureItems to update.
   */
  where: Prisma.VaultSecureItemsWhereUniqueInput
}

/**
 * VaultSecureItems updateMany
 */
export type VaultSecureItemsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VaultSecureItems.
   */
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateManyMutationInput, Prisma.VaultSecureItemsUncheckedUpdateManyInput>
  /**
   * Filter which VaultSecureItems to update
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * Limit how many VaultSecureItems to update.
   */
  limit?: number
}

/**
 * VaultSecureItems updateManyAndReturn
 */
export type VaultSecureItemsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * The data used to update VaultSecureItems.
   */
  data: Prisma.XOR<Prisma.VaultSecureItemsUpdateManyMutationInput, Prisma.VaultSecureItemsUncheckedUpdateManyInput>
  /**
   * Filter which VaultSecureItems to update
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * Limit how many VaultSecureItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VaultSecureItems upsert
 */
export type VaultSecureItemsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * The filter to search for the VaultSecureItems to update in case it exists.
   */
  where: Prisma.VaultSecureItemsWhereUniqueInput
  /**
   * In case the VaultSecureItems found by the `where` argument doesn't exist, create a new VaultSecureItems with this data.
   */
  create: Prisma.XOR<Prisma.VaultSecureItemsCreateInput, Prisma.VaultSecureItemsUncheckedCreateInput>
  /**
   * In case the VaultSecureItems was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VaultSecureItemsUpdateInput, Prisma.VaultSecureItemsUncheckedUpdateInput>
}

/**
 * VaultSecureItems delete
 */
export type VaultSecureItemsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
  /**
   * Filter which VaultSecureItems to delete.
   */
  where: Prisma.VaultSecureItemsWhereUniqueInput
}

/**
 * VaultSecureItems deleteMany
 */
export type VaultSecureItemsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VaultSecureItems to delete
   */
  where?: Prisma.VaultSecureItemsWhereInput
  /**
   * Limit how many VaultSecureItems to delete.
   */
  limit?: number
}

/**
 * VaultSecureItems without action
 */
export type VaultSecureItemsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VaultSecureItems
   */
  select?: Prisma.VaultSecureItemsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VaultSecureItems
   */
  omit?: Prisma.VaultSecureItemsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VaultSecureItemsInclude<ExtArgs> | null
}
